# This file is automatically generated by scripts/generate_exceptions.
# It is not intended for manual editing.
"""A common error type used by many functions in this package.

TODO: In the future this should be split up into more-specific error
enums so that it better documents which errors each function can actually
return and what they mean.
"""

from fastly_compute.exceptions import FastlyError


class Error(FastlyError):
    """A common error type used by many functions in this package.

    TODO: In the future this should be split up into more-specific error
    enums so that it better documents which errors each function can actually
    return and what they mean.
    """


class GenericError(Error):
    """Generic error value.

    This means that some unexpected error occurred.
    """


class InvalidArgument(Error):
    """Invalid argument."""


class AuxiliaryError(Error):
    """Auxiliary error value.

    For `cache.get-body` and `cache.replace-get-body`, it means the cache implementation was
    busy and not ready to retrieve the body data.

    For cache APIs that attempt to write to or update the body of a cache transaction, it means
    that an error occurred while attempting the write or update.

    For other cache APIs, it indicates that the underlying cache entry or cache replace entry
    is no longer available.

    For writing to a streaming HTTP body, indicates that the body has already been closed.

    For a dictionary lookup, indicates that the dictionary was not found.
    """


class Unsupported(Error):
    """Unsupported operation error.

    This error is returned when some operation cannot be performed, because it is not supported.
    """


class HttpInvalid(Error):
    """Invalid HTTP error.

    This can be returned when a method, URI, header, or status is not valid. This can also
    be returned if a message head is too large.
    """


class HttpUser(Error):
    """HTTP user error.

    This is returned in cases where user code caused an HTTP error. For example, attempt to send
    a 1xx response code, or a request with a non-absolute URI. This can also be caused by
    an unexpected header: both `content-length` and `transfer-encoding`, for example.
    """


class HttpIncomplete(Error):
    """HTTP incomplete message error.

    This can be returned when a stream ended unexpectedly.
    """


class CannotRead(Error):
    """Cannot read.

    An error occurred while attempting to read the body of a cache transaction.
    """


class HttpHeadTooLarge(Error):
    """Message head too large."""


class HttpInvalidStatus(Error):
    """Invalid HTTP status."""


class LimitExceeded(Error):
    """Limit exceeded

    This is returned when an attempt to allocate a resource has exceeded the maximum number of
    resources permitted. For example, creating too many response handles.
    """


class BufferLen(Error):
    """Buffer length error

    Returned when a buffer is the wrong size.
    Includes the buffer length that would allow the operation to succeed.
    """

    def __init__(self, wit_error):
        self.length = wit_error.value

    def __str__(self):
        return f"Buffer was too short to hold the result. At least {self.length} bytes are needed."
