# This file is automatically generated by scripts/generate_exceptions.
# It is not intended for manual editing.
"""An error returned by `open`-like functions."""

from fastly_compute.exceptions import FastlyError


class OpenError(FastlyError):
    """An error returned by `open`-like functions."""


class InvalidSyntax(OpenError):
    """The given name of the entity to open was invalid."""


class NameTooLong(OpenError):
    """The given name is longer the maximum permitted length."""


class Reserved(OpenError):
    """The given name is a reserved name that may not be opened."""


class NotFound(OpenError):
    """No entity by the given name was found."""


class Unsupported(OpenError):
    """Unsupported operation error.

    This error is returned when some operation cannot be performed, because it is not supported.
    """


class LimitExceeded(OpenError):
    """Limit exceeded

    This is returned when an attempt to allocate a resource has exceeded the maximum number of
    resources permitted. For example, creating too many response handles.
    """


class GenericError(OpenError):
    """Generic error value.

    This means that some unexpected error occurred.
    """
