# This file is automatically generated by generate_patches.
# It is not intended for manual editing.
"""Monkeypatches which wrap the routines generated by componentize-py to make
them raise more specific exceptions, not just Err.
"""

try:
    import wit_world.imports.acl
    import wit_world.imports.backend
    import wit_world.imports.cache
    import wit_world.imports.config_store
    import wit_world.imports.device_detection
    import wit_world.imports.dictionary
    import wit_world.imports.erl
    import wit_world.imports.geo
    import wit_world.imports.http_body
    import wit_world.imports.http_cache
    import wit_world.imports.http_downstream
    import wit_world.imports.http_req
    import wit_world.imports.http_resp
    import wit_world.imports.image_optimizer
    import wit_world.imports.kv_store
    import wit_world.imports.log
    import wit_world.imports.purge
    import wit_world.imports.secret_store
    import wit_world.imports.security
    import wit_world.imports.shielding
    import wit_world.imports.types

    import fastly_compute.exceptions.acl.acl_error
    import fastly_compute.exceptions.http_body.trailer_error
    import fastly_compute.exceptions.http_req
    import fastly_compute.exceptions.kv_store.kv_error
    import fastly_compute.exceptions.types.error
    import fastly_compute.exceptions.types.open_error

    from .decorators import remap_wit_errors
except ImportError:
    # Tolerate that momentary import for the testrunner before Viceroy, and thus
    # the wit_world, is around.
    def patch():
        """Pretend to patch."""
        print("Faking the run of exception-mapping monkeypatches for test runner.")
else:
    MAPPINGS = {
        wit_world.imports.acl.AclError.GENERIC_ERROR: fastly_compute.exceptions.acl.acl_error.GenericError,
        wit_world.imports.acl.AclError.TOO_MANY_REQUESTS: fastly_compute.exceptions.acl.acl_error.TooManyRequests,
        wit_world.imports.http_body.TrailerError_Error: fastly_compute.exceptions.http_body.trailer_error.Error,
        wit_world.imports.http_body.TrailerError_NotAvailableYet: fastly_compute.exceptions.http_body.trailer_error.NotAvailableYet,
        wit_world.imports.http_req.ErrorWithDetail: fastly_compute.exceptions.http_req.ErrorWithDetail,
        wit_world.imports.kv_store.KvError_BadRequest: fastly_compute.exceptions.kv_store.kv_error.BadRequest,
        wit_world.imports.kv_store.KvError_Extra: fastly_compute.exceptions.kv_store.kv_error.Extra,
        wit_world.imports.kv_store.KvError_GenericError: fastly_compute.exceptions.kv_store.kv_error.GenericError,
        wit_world.imports.kv_store.KvError_InternalError: fastly_compute.exceptions.kv_store.kv_error.InternalError,
        wit_world.imports.kv_store.KvError_PayloadTooLarge: fastly_compute.exceptions.kv_store.kv_error.PayloadTooLarge,
        wit_world.imports.kv_store.KvError_PreconditionFailed: fastly_compute.exceptions.kv_store.kv_error.PreconditionFailed,
        wit_world.imports.kv_store.KvError_TooManyRequests: fastly_compute.exceptions.kv_store.kv_error.TooManyRequests,
        wit_world.imports.types.Error_AuxiliaryError: fastly_compute.exceptions.types.error.AuxiliaryError,
        wit_world.imports.types.Error_BufferLen: fastly_compute.exceptions.types.error.BufferLen,
        wit_world.imports.types.Error_CannotRead: fastly_compute.exceptions.types.error.CannotRead,
        wit_world.imports.types.Error_GenericError: fastly_compute.exceptions.types.error.GenericError,
        wit_world.imports.types.Error_HttpHeadTooLarge: fastly_compute.exceptions.types.error.HttpHeadTooLarge,
        wit_world.imports.types.Error_HttpIncomplete: fastly_compute.exceptions.types.error.HttpIncomplete,
        wit_world.imports.types.Error_HttpInvalid: fastly_compute.exceptions.types.error.HttpInvalid,
        wit_world.imports.types.Error_HttpInvalidStatus: fastly_compute.exceptions.types.error.HttpInvalidStatus,
        wit_world.imports.types.Error_HttpUser: fastly_compute.exceptions.types.error.HttpUser,
        wit_world.imports.types.Error_InvalidArgument: fastly_compute.exceptions.types.error.InvalidArgument,
        wit_world.imports.types.Error_LimitExceeded: fastly_compute.exceptions.types.error.LimitExceeded,
        wit_world.imports.types.Error_Unsupported: fastly_compute.exceptions.types.error.Unsupported,
        wit_world.imports.types.OpenError.GENERIC_ERROR: fastly_compute.exceptions.types.open_error.GenericError,
        wit_world.imports.types.OpenError.INVALID_SYNTAX: fastly_compute.exceptions.types.open_error.InvalidSyntax,
        wit_world.imports.types.OpenError.LIMIT_EXCEEDED: fastly_compute.exceptions.types.open_error.LimitExceeded,
        wit_world.imports.types.OpenError.NAME_TOO_LONG: fastly_compute.exceptions.types.open_error.NameTooLong,
        wit_world.imports.types.OpenError.NOT_FOUND: fastly_compute.exceptions.types.open_error.NotFound,
        wit_world.imports.types.OpenError.RESERVED: fastly_compute.exceptions.types.open_error.Reserved,
        wit_world.imports.types.OpenError.UNSUPPORTED: fastly_compute.exceptions.types.open_error.Unsupported,
        type(None): fastly_compute.exceptions.FastlyError,
    }

    did_patch = False

    def patch():
        """Apply patches if they haven't already been applied."""
        global did_patch
        if did_patch:
            # This test shouldn't be needed, but it avoids double-wrapping the
            # routines if somehow patch() did get called twice.
            return
        did_patch = True
        wit_world.imports.log.Endpoint.open = remap_wit_errors(MAPPINGS)(wit_world.imports.log.Endpoint.open)
        wit_world.imports.dictionary.Dictionary.open = remap_wit_errors(MAPPINGS)(wit_world.imports.dictionary.Dictionary.open)
        wit_world.imports.dictionary.Dictionary.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.dictionary.Dictionary.lookup)
        wit_world.imports.geo.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.geo.lookup)
        wit_world.imports.device_detection.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.device_detection.lookup)
        wit_world.imports.erl.RateCounter.open = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.RateCounter.open)
        wit_world.imports.erl.RateCounter.check_rate = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.RateCounter.check_rate)
        wit_world.imports.erl.RateCounter.increment = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.RateCounter.increment)
        wit_world.imports.erl.RateCounter.lookup_rate = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.RateCounter.lookup_rate)
        wit_world.imports.erl.RateCounter.lookup_count = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.RateCounter.lookup_count)
        wit_world.imports.erl.PenaltyBox.open = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.PenaltyBox.open)
        wit_world.imports.erl.PenaltyBox.add = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.PenaltyBox.add)
        wit_world.imports.erl.PenaltyBox.has = remap_wit_errors(MAPPINGS)(wit_world.imports.erl.PenaltyBox.has)
        wit_world.imports.secret_store.Secret.from_bytes = remap_wit_errors(MAPPINGS)(wit_world.imports.secret_store.Secret.from_bytes)
        wit_world.imports.secret_store.Secret.plaintext = remap_wit_errors(MAPPINGS)(wit_world.imports.secret_store.Secret.plaintext)
        wit_world.imports.secret_store.Store.open = remap_wit_errors(MAPPINGS)(wit_world.imports.secret_store.Store.open)
        wit_world.imports.secret_store.Store.get = remap_wit_errors(MAPPINGS)(wit_world.imports.secret_store.Store.get)
        wit_world.imports.backend.register_dynamic_backend = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.register_dynamic_backend)
        wit_world.imports.backend.Backend.open = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.open)
        wit_world.imports.backend.Backend.is_healthy = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.is_healthy)
        wit_world.imports.backend.Backend.is_dynamic = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.is_dynamic)
        wit_world.imports.backend.Backend.get_host = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_host)
        wit_world.imports.backend.Backend.get_override_host = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_override_host)
        wit_world.imports.backend.Backend.get_port = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_port)
        wit_world.imports.backend.Backend.get_connect_timeout_ms = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_connect_timeout_ms)
        wit_world.imports.backend.Backend.get_first_byte_timeout_ms = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_first_byte_timeout_ms)
        wit_world.imports.backend.Backend.get_between_bytes_timeout_ms = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_between_bytes_timeout_ms)
        wit_world.imports.backend.Backend.is_tls = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.is_tls)
        wit_world.imports.backend.Backend.get_tls_min_version = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tls_min_version)
        wit_world.imports.backend.Backend.get_tls_max_version = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tls_max_version)
        wit_world.imports.backend.Backend.get_http_keepalive_time = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_http_keepalive_time)
        wit_world.imports.backend.Backend.get_tcp_keepalive_enable = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tcp_keepalive_enable)
        wit_world.imports.backend.Backend.get_tcp_keepalive_interval = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tcp_keepalive_interval)
        wit_world.imports.backend.Backend.get_tcp_keepalive_probes = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tcp_keepalive_probes)
        wit_world.imports.backend.Backend.get_tcp_keepalive_time = remap_wit_errors(MAPPINGS)(wit_world.imports.backend.Backend.get_tcp_keepalive_time)
        wit_world.imports.http_body.new = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.new)
        wit_world.imports.http_body.append = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.append)
        wit_world.imports.http_body.read = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.read)
        wit_world.imports.http_body.write = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.write)
        wit_world.imports.http_body.write_front = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.write_front)
        wit_world.imports.http_body.close = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.close)
        wit_world.imports.http_body.append_trailer = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.append_trailer)
        wit_world.imports.http_body.get_trailer_names = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.get_trailer_names)
        wit_world.imports.http_body.get_trailer_value = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.get_trailer_value)
        wit_world.imports.http_body.get_trailer_values = remap_wit_errors(MAPPINGS)(wit_world.imports.http_body.get_trailer_values)
        wit_world.imports.http_resp.Response.new = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.new)
        wit_world.imports.http_resp.Response.get_header_names = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.get_header_names)
        wit_world.imports.http_resp.Response.get_header_value = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.get_header_value)
        wit_world.imports.http_resp.Response.get_header_values = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.get_header_values)
        wit_world.imports.http_resp.Response.set_header_values = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.set_header_values)
        wit_world.imports.http_resp.Response.insert_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.insert_header)
        wit_world.imports.http_resp.Response.append_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.append_header)
        wit_world.imports.http_resp.Response.remove_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.remove_header)
        wit_world.imports.http_resp.Response.get_version = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.get_version)
        wit_world.imports.http_resp.Response.set_version = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.set_version)
        wit_world.imports.http_resp.Response.get_status = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.get_status)
        wit_world.imports.http_resp.Response.set_status = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.set_status)
        wit_world.imports.http_resp.Response.set_framing_headers_mode = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.set_framing_headers_mode)
        wit_world.imports.http_resp.Response.set_http_keepalive_mode = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.Response.set_http_keepalive_mode)
        wit_world.imports.http_resp.send_downstream = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.send_downstream)
        wit_world.imports.http_resp.send_downstream_streaming = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.send_downstream_streaming)
        wit_world.imports.http_resp.close = remap_wit_errors(MAPPINGS)(wit_world.imports.http_resp.close)
        wit_world.imports.http_req.Request.new = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.new)
        wit_world.imports.http_req.Request.set_cache_override = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_cache_override)
        wit_world.imports.http_req.Request.get_header_names = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_header_names)
        wit_world.imports.http_req.Request.get_header_value = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_header_value)
        wit_world.imports.http_req.Request.get_header_values = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_header_values)
        wit_world.imports.http_req.Request.set_header_values = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_header_values)
        wit_world.imports.http_req.Request.insert_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.insert_header)
        wit_world.imports.http_req.Request.append_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.append_header)
        wit_world.imports.http_req.Request.remove_header = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.remove_header)
        wit_world.imports.http_req.Request.get_method = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_method)
        wit_world.imports.http_req.Request.set_method = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_method)
        wit_world.imports.http_req.Request.get_uri = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_uri)
        wit_world.imports.http_req.Request.set_uri = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_uri)
        wit_world.imports.http_req.Request.get_version = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.get_version)
        wit_world.imports.http_req.Request.set_version = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_version)
        wit_world.imports.http_req.Request.set_auto_decompress_response = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_auto_decompress_response)
        wit_world.imports.http_req.Request.redirect_to_websocket_proxy = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.redirect_to_websocket_proxy)
        wit_world.imports.http_req.Request.set_framing_headers_mode = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.set_framing_headers_mode)
        wit_world.imports.http_req.Request.redirect_to_grip_proxy = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.Request.redirect_to_grip_proxy)
        wit_world.imports.http_req.send = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send)
        wit_world.imports.http_req.send_uncached = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send_uncached)
        wit_world.imports.http_req.send_async = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send_async)
        wit_world.imports.http_req.send_async_uncached = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send_async_uncached)
        wit_world.imports.http_req.send_async_streaming = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send_async_streaming)
        wit_world.imports.http_req.send_async_uncached_streaming = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.send_async_uncached_streaming)
        wit_world.imports.http_req.await_response = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.await_response)
        wit_world.imports.http_req.close = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.close)
        wit_world.imports.http_req.upgrade_websocket = remap_wit_errors(MAPPINGS)(wit_world.imports.http_req.upgrade_websocket)
        wit_world.imports.http_downstream.next_request = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.next_request)
        wit_world.imports.http_downstream.await_request = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.await_request)
        wit_world.imports.http_downstream.downstream_original_header_names = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_original_header_names)
        wit_world.imports.http_downstream.downstream_original_header_count = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_original_header_count)
        wit_world.imports.http_downstream.downstream_client_h2_fingerprint = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_client_h2_fingerprint)
        wit_world.imports.http_downstream.downstream_client_request_id = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_client_request_id)
        wit_world.imports.http_downstream.downstream_client_oh_fingerprint = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_client_oh_fingerprint)
        wit_world.imports.http_downstream.downstream_client_ddos_detected = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_client_ddos_detected)
        wit_world.imports.http_downstream.downstream_tls_cipher_openssl_name = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_cipher_openssl_name)
        wit_world.imports.http_downstream.downstream_tls_protocol = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_protocol)
        wit_world.imports.http_downstream.downstream_tls_client_hello = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_client_hello)
        wit_world.imports.http_downstream.downstream_tls_raw_client_certificate = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_raw_client_certificate)
        wit_world.imports.http_downstream.downstream_tls_client_cert_verify_result = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_client_cert_verify_result)
        wit_world.imports.http_downstream.downstream_tls_client_servername = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_client_servername)
        wit_world.imports.http_downstream.downstream_tls_ja3_md5 = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_ja3_md5)
        wit_world.imports.http_downstream.downstream_tls_ja4 = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_tls_ja4)
        wit_world.imports.http_downstream.downstream_compliance_region = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.downstream_compliance_region)
        wit_world.imports.http_downstream.fastly_key_is_valid = remap_wit_errors(MAPPINGS)(wit_world.imports.http_downstream.fastly_key_is_valid)
        wit_world.imports.security.inspect = remap_wit_errors(MAPPINGS)(wit_world.imports.security.inspect)
        wit_world.imports.kv_store.Store.open = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.open)
        wit_world.imports.kv_store.Store.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.lookup)
        wit_world.imports.kv_store.Store.lookup_async = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.lookup_async)
        wit_world.imports.kv_store.Store.insert = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.insert)
        wit_world.imports.kv_store.Store.insert_async = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.insert_async)
        wit_world.imports.kv_store.Store.delete = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.delete)
        wit_world.imports.kv_store.Store.delete_async = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.delete_async)
        wit_world.imports.kv_store.Store.list = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.list)
        wit_world.imports.kv_store.Store.list_async = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Store.list_async)
        wit_world.imports.kv_store.await_lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.await_lookup)
        wit_world.imports.kv_store.await_insert = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.await_insert)
        wit_world.imports.kv_store.await_delete = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.await_delete)
        wit_world.imports.kv_store.await_list = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.await_list)
        wit_world.imports.kv_store.Entry.metadata = remap_wit_errors(MAPPINGS)(wit_world.imports.kv_store.Entry.metadata)
        wit_world.imports.acl.Acl.open = remap_wit_errors(MAPPINGS)(wit_world.imports.acl.Acl.open)
        wit_world.imports.acl.Acl.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.acl.Acl.lookup)
        wit_world.imports.purge.purge_surrogate_key = remap_wit_errors(MAPPINGS)(wit_world.imports.purge.purge_surrogate_key)
        wit_world.imports.purge.purge_surrogate_key_verbose = remap_wit_errors(MAPPINGS)(wit_world.imports.purge.purge_surrogate_key_verbose)
        wit_world.imports.cache.Entry.lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.lookup)
        wit_world.imports.cache.Entry.transaction_lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_lookup)
        wit_world.imports.cache.Entry.transaction_lookup_async = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_lookup_async)
        wit_world.imports.cache.Entry.transaction_insert = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_insert)
        wit_world.imports.cache.Entry.transaction_insert_and_stream_back = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_insert_and_stream_back)
        wit_world.imports.cache.Entry.transaction_update = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_update)
        wit_world.imports.cache.Entry.get_state = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_state)
        wit_world.imports.cache.Entry.get_user_metadata = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_user_metadata)
        wit_world.imports.cache.Entry.get_body = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_body)
        wit_world.imports.cache.Entry.get_length = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_length)
        wit_world.imports.cache.Entry.get_max_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_max_age_ns)
        wit_world.imports.cache.Entry.get_stale_while_revalidate_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_stale_while_revalidate_ns)
        wit_world.imports.cache.Entry.get_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_age_ns)
        wit_world.imports.cache.Entry.get_hits = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.get_hits)
        wit_world.imports.cache.Entry.transaction_cancel = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.Entry.transaction_cancel)
        wit_world.imports.cache.ReplaceEntry.replace = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.replace)
        wit_world.imports.cache.ReplaceEntry.get_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_age_ns)
        wit_world.imports.cache.ReplaceEntry.get_body = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_body)
        wit_world.imports.cache.ReplaceEntry.get_hits = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_hits)
        wit_world.imports.cache.ReplaceEntry.get_length = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_length)
        wit_world.imports.cache.ReplaceEntry.get_max_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_max_age_ns)
        wit_world.imports.cache.ReplaceEntry.get_stale_while_revalidate_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_stale_while_revalidate_ns)
        wit_world.imports.cache.ReplaceEntry.get_state = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_state)
        wit_world.imports.cache.ReplaceEntry.get_user_metadata = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.ReplaceEntry.get_user_metadata)
        wit_world.imports.cache.insert = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.insert)
        wit_world.imports.cache.await_entry = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.await_entry)
        wit_world.imports.cache.close_pending_entry = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.close_pending_entry)
        wit_world.imports.cache.close_entry = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.close_entry)
        wit_world.imports.cache.replace_insert = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.replace_insert)
        wit_world.imports.cache.close_replace_entry = remap_wit_errors(MAPPINGS)(wit_world.imports.cache.close_replace_entry)
        wit_world.imports.http_cache.Entry.transaction_lookup = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_lookup)
        wit_world.imports.http_cache.Entry.transaction_insert = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_insert)
        wit_world.imports.http_cache.Entry.transaction_insert_and_stream_back = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_insert_and_stream_back)
        wit_world.imports.http_cache.Entry.transaction_update = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_update)
        wit_world.imports.http_cache.Entry.transaction_update_and_return_fresh = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_update_and_return_fresh)
        wit_world.imports.http_cache.Entry.transaction_record_not_cacheable = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_record_not_cacheable)
        wit_world.imports.http_cache.Entry.get_suggested_backend_request = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_suggested_backend_request)
        wit_world.imports.http_cache.Entry.get_suggested_write_options = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_suggested_write_options)
        wit_world.imports.http_cache.Entry.prepare_response_for_storage = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.prepare_response_for_storage)
        wit_world.imports.http_cache.Entry.get_found_response = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_found_response)
        wit_world.imports.http_cache.Entry.get_state = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_state)
        wit_world.imports.http_cache.Entry.get_length = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_length)
        wit_world.imports.http_cache.Entry.get_max_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_max_age_ns)
        wit_world.imports.http_cache.Entry.get_stale_while_revalidate_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_stale_while_revalidate_ns)
        wit_world.imports.http_cache.Entry.get_age_ns = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_age_ns)
        wit_world.imports.http_cache.Entry.get_hits = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_hits)
        wit_world.imports.http_cache.Entry.get_sensitive_data = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_sensitive_data)
        wit_world.imports.http_cache.Entry.get_surrogate_keys = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_surrogate_keys)
        wit_world.imports.http_cache.Entry.get_vary_rule = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.get_vary_rule)
        wit_world.imports.http_cache.Entry.transaction_abandon = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.Entry.transaction_abandon)
        wit_world.imports.http_cache.is_request_cacheable = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.is_request_cacheable)
        wit_world.imports.http_cache.get_suggested_cache_key = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.get_suggested_cache_key)
        wit_world.imports.http_cache.close_entry = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.close_entry)
        wit_world.imports.http_cache.SuggestedWriteOptions.get_vary_rule = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.SuggestedWriteOptions.get_vary_rule)
        wit_world.imports.http_cache.SuggestedWriteOptions.get_surrogate_keys = remap_wit_errors(MAPPINGS)(wit_world.imports.http_cache.SuggestedWriteOptions.get_surrogate_keys)
        wit_world.imports.config_store.Store.open = remap_wit_errors(MAPPINGS)(wit_world.imports.config_store.Store.open)
        wit_world.imports.config_store.Store.get = remap_wit_errors(MAPPINGS)(wit_world.imports.config_store.Store.get)
        wit_world.imports.shielding.shield_info = remap_wit_errors(MAPPINGS)(wit_world.imports.shielding.shield_info)
        wit_world.imports.shielding.backend_for_shield = remap_wit_errors(MAPPINGS)(wit_world.imports.shielding.backend_for_shield)
        wit_world.imports.image_optimizer.transform_image_optimizer_request = remap_wit_errors(MAPPINGS)(wit_world.imports.image_optimizer.transform_image_optimizer_request)
