# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Blocklists using [Access Control Lists] (ACLs)

[Access Control Lists]: https://www.fastly.com/documentation/reference/api/acls/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import async_io
from ..imports import types

class AclError(Enum):
    """
    Errors returned on ACL lookup failure.
    """
    TOO_MANY_REQUESTS = 0
    GENERIC_ERROR = 1

class Acl:
    """
    An ACL.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens an ACL linked to the current service with the given link name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def lookup(self, ip_addr: types.IpAddress) -> Optional[async_io.Pollable]:
        """
        Performs a lookup of the given IP address in the ACL.
        
        If any matches are found, the result is a JSON-encoded HTTP body.
        
        If no matches are found, then `ok(none)` is returned. This corresponds
        to an HTTP error code of 204, “No Content”.
        
        Raises: `wit_world.types.Err(wit_world.imports.acl.AclError)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



