# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Core Cache] API

[Core Cache]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/#core-cache
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import async_io
from ..imports import http_req

class ExtraLookupOptions:
    """
    Extensibility for `lookup-options`
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class LookupOptions:
    """
    Options for cache lookup operations; currently used for both `lookup` and
    `transaction-lookup`.
    """
    request_headers: Optional[http_req.Request]
    always_use_requested_range: bool
    extra: Optional[ExtraLookupOptions]

class ExtraWriteOptions:
    """
    Extensibility for `write-options`
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class WriteOptions:
    """
    Configuration for several functions that write to the cache:
    - `insert`
    - `transaction-insert`
    - `transaction-insert-and-stream-back`
    - `transaction-update`
    
    Some options are only allowed for certain of these hostcalls; see the comments
    on the fields.
    """
    max_age_ns: int
    request_headers: Optional[http_req.Request]
    vary_rule: Optional[str]
    initial_age_ns: Optional[int]
    stale_while_revalidate_ns: Optional[int]
    surrogate_keys: Optional[str]
    length: Optional[int]
    user_metadata: Optional[bytes]
    edge_max_age_ns: Optional[int]
    sensitive_data: bool
    extra: Optional[ExtraWriteOptions]

class LookupState(Flag):
    """
    The status of this lookup (and potential transaction)
    """
    FOUND = auto()
    USABLE = auto()
    STALE = auto()
    MUST_INSERT_OR_UPDATE = auto()
    USABLE_IF_ERROR = auto()

class ExtraGetBodyOptions:
    """
    Extensibility for `get-body-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class GetBodyOptions:
    from_: Optional[int]
    to: Optional[int]
    extra: Optional[ExtraGetBodyOptions]

class Entry:
    """
    The outcome of a cache lookup (either bare or as part of a cache transaction)
    """
    
    @classmethod
    def lookup(cls, key: bytes, options: LookupOptions) -> Self:
        """
        Performs a non-request-collapsing cache lookup.
        
        Returns a result without waiting for any request collapsing that may be ongoing.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    @classmethod
    def transaction_lookup(cls, key: bytes, options: LookupOptions) -> Self:
        """
        The entrypoint to the request-collapsing cache transaction API.
        
        This operation always participates in request collapsing and may return stale objects. To
        bypass request collapsing, use `entry.lookup` or `insert` instead.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    @classmethod
    def transaction_lookup_async(cls, key: bytes, options: LookupOptions) -> async_io.Pollable:
        """
        The entrypoint to the request-collapsing cache transaction API, returning instead of waiting
        on busy.
        
        This operation always participates in request collapsing and may return stale objects. To
        bypass request collapsing, use `entry.lookup` or `insert` instead.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_insert(self, options: WriteOptions) -> async_io.Pollable:
        """
        Inserts an object into the cache with the given metadata.
        
        Can only be used in if the cache handle state includes the `must-insert-or-update` flag.
        
        The returned handle is to a streaming body that is used for writing the object into
        the cache.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_insert_and_stream_back(self, options: WriteOptions) -> Tuple[async_io.Pollable, Self]:
        """
        Inserts an object into the cache with the given metadata, and return a readable stream of the
        bytes as they are stored.
        
        This helps avoid the “slow reader” problem on a teed stream, for example when a program
        wishes to store a backend request in the cache while simultaneously streaming to a client
        in an HTTP response.
        
        The returned body handle is to a streaming body that is used for writing the object *into*
        the cache. The returned cache handle provides a separate transaction for reading out the
        newly cached object to send elsewhere.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_update(self, options: WriteOptions) -> None:
        """
        Update the metadata of an object in the cache without changing its data.
        
        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must-insert-or-update`
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_state(self) -> LookupState:
        """
        Get the state of a cache lookup, waiting for the lookup to complete if necessary.
        
        Note that FOUND == USABLE, and means "usable" (fresh or stale-while-revalidate).
        Some SDKs were released that checked only FOUND to infer "usable";
        we preserve the equivalence for backwards compatibility.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_user_metadata(self, max_len: int) -> Optional[bytes]:
        """
        Gets the user metadata of the found object, returning `ok(none)` if no object
        was found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_body(self, options: GetBodyOptions) -> async_io.Pollable:
        """
        Gets a range of the found object body, returning `ok(none)` if there
        was no found object.
        
        The returned `body` must be closed before calling this function again on the same
        `entry`.
        
        Note: until the CacheD protocol is adjusted to fully support this functionality,
        the body of objects that are past the stale-while-revalidate period will not
        be available, even when other metadata is.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_length(self) -> Optional[int]:
        """
        Gets the content length of the found object, returning `ok(none)` if
        there was no found object, or no content length was provided.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_max_age_ns(self) -> Optional[int]:
        """
        Gets the configured max age of the found object, returning `ok(none)`
        if there was no found object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_stale_while_revalidate_ns(self) -> Optional[int]:
        """
        Gets the configured stale-while-revalidate period of the found object, returning `ok(none)`
        if there was no found object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_age_ns(self) -> Optional[int]:
        """
        Gets the age of the found object, returning `ok(none)` if there
        was no found object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_hits(self) -> Optional[int]:
        """
        Gets the number of cache hits for the found object, returning `ok(none)`
        if there was no found object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_cancel(self) -> None:
        """
        Cancel an obligation to provide an object to the cache.
        
        Useful if there is an error before streaming is possible, for example if a backend is
        unreachable.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class ReplaceStrategy(Enum):
    IMMEDIATE = 0
    IMMEDIATE_FORCE_MISS = 1
    WAIT = 2

class ExtraReplaceOptions:
    """
    Extensibility for `replace-options`
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class ReplaceOptions:
    """
    Options for cache replace operations
    """
    request_headers: Optional[http_req.Request]
    replace_strategy: Optional[ReplaceStrategy]
    always_use_requested_range: bool
    extra: Optional[ExtraReplaceOptions]

class ReplaceEntry:
    """
    A replace operation.
    """
    
    @classmethod
    def replace(cls, key: bytes, options: ReplaceOptions) -> Self:
        """
        The entrypoint to the replace API.
        
        This operation always participates in request collapsing and may return stale objects.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_age_ns(self) -> Optional[int]:
        """
        Gets the age of the existing object during replace, returning
        `ok(none)` if there was no object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_body(self, options: GetBodyOptions) -> Optional[async_io.Pollable]:
        """
        Gets a range of the existing object body, returning `ok(none)` if there
        was no existing object.
        
        The returned `body` must be closed before calling this function
        again on the same `replace-entry`.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_hits(self) -> Optional[int]:
        """
        Gets the number of cache hits for the existing object during replace,
        returning `ok(none)` if there was no object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_length(self) -> Optional[int]:
        """
        Gets the content length of the existing object during replace,
        returning `ok(none)` if there was no object, or no content
        length was provided.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_max_age_ns(self) -> Optional[int]:
        """
        Gets the configured max age of the existing object during replace,
        returning `ok(none)` if there was no object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_stale_while_revalidate_ns(self) -> Optional[int]:
        """
        Gets the configured stale-while-revalidate period of the existing
        object during replace, returning `ok(none)` if there was no
        object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_state(self) -> Optional[LookupState]:
        """
        Gets the lookup state of the existing object during replace, returning
        `ok(none)` if there was no object.
        
        Note that FOUND == USABLE, and means "usable" (fresh or stale-while-revalidate).
        Some SDKs were released that checked only FOUND to infer "usable";
        we preserve the equivalence for backwards compatibility.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_user_metadata(self, max_len: int) -> Optional[bytes]:
        """
        Gets the user metadata of the existing object during replace, returning
        `ok(none)` if there was no object.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def insert(key: bytes, options: WriteOptions) -> async_io.Pollable:
    """
    Performs a non-request-collapsing cache insertion (or update).
    
    The returned handle is to a streaming body that is used for writing the object into
    the cache.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def await_entry(handle: async_io.Pollable) -> Entry:
    """
    Continues the lookup transaction from which the given busy handle was returned,
    waiting for the leader transaction if request collapsed, and returns a cache handle.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close_pending_entry(handle: async_io.Pollable) -> None:
    """
    Closes an interaction with the cache that has not yet finished request collapsing.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close_entry(handle: Entry) -> None:
    """
    Closes an ongoing interaction with the cache.
    
    If the cache handle state includes the `must-insert-or-update` (and hence no insert or
    update has been performed), closing the handle cancels any request collapsing, potentially
    choosing a new waiter to perform the insertion/update.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def replace_insert(handle: ReplaceEntry, options: WriteOptions) -> async_io.Pollable:
    """
    Replace an object in the cache with the given metadata
    
    The returned handle is to a streaming body that is used for writing the object into
    the cache.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close_replace_entry(handle: ReplaceEntry) -> None:
    """
    Closes an ongoing replace interaction with the cache.
    
    If the replace handle state includes the `must-insert-or-update` (and hence no insert or
    update has been performed), closing the handle cancels any request collapsing, potentially
    choosing a new waiter to perform the insertion/update.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
