# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Features for interacting with the Compute runtime.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def get_vcpu_ms() -> int:
    """
    Gets the amount of vCPU time that has passed since this sandbox was started, in
    milliseconds.
    
    This function returns only time spent running on a vCPU, and does not include time spent
    performing any I/O operations. However, it is based on clock time passing, and so will include
    time spent executing hostcalls, is heavily affected by what core of what CPU is running the
    code, and can even be influenced by the state of the CPU.
    
    As a result, this function *should not be used in benchmarking across runs*. It can be used,
    with caution, to compare the runtime of different operations within the same sandbox.
    """
    raise NotImplementedError
def get_heap_mib() -> int:
    """
    Get a snapshot of the current dynamic memory usage, rounded up to the nearest mebibyte (2^20).
    
    This includes usage from the Wasm linear memory (heap) and usage from host allocations
    made on behalf of this sandbox, e.g. buffered bodies of HTTP responses.
    The returned value is just a snapshot- it can change without any explicit action
    by the sandbox (for instance, additional response data coming in from an HTTP response.)
    It can also change over time / across runs, as the Compute platform's memory usage
    changes. Consider the returned value with these uncertainties in mind.
    """
    raise NotImplementedError
def get_sandbox_id() -> str:
    """
    A UUID generated by Fastly for each sandbox.
    
    This is often a useful value to include in log messages, and also to send to upstream
    servers as an additional custom HTTP header, allowing for straightforward correlation of
    which sandbox processed a request to requests later processed by an origin server.
    
    By default, each sandbox handles exactly one downstream request, in which case
    this sandbox UUID is unique for each request. However, by using
    `http-downstream.next-request`, a single sandbox can accept multiple downstream
    requests. For a UUID that reliably identifies a request, you may wish to use
    `http-downstream.downstream-client-request-id`.
    
    Equivalent to the "FASTLY_TRACE_ID" environment variable.
    """
    raise NotImplementedError
def get_hostname() -> str:
    """
    The hostname of the Fastly cache server which is executing the current sandbox, for
    example, `cache-jfk1034`.
    
    Equivalent to the "FASTLY_HOSTNAME" environment variable and to [`server.hostname`] in VCL.
    
    [`server.hostname`]: https://www.fastly.com/documentation/reference/vcl/variables/server/server-hostname/
    """
    raise NotImplementedError
def get_pop() -> str:
    """
    The three-character identifying code of the [Fastly POP] in which the current service
    instance is running.
    
    Equivalent to the "FASTLY_POP" environment variable and to [`server.datacenter`] in VCL.
    
    [Fastly POP]: https://www.fastly.com/documentation/guides/concepts/pop/
    [`server.datacenter`]: https://www.fastly.com/documentation/reference/vcl/variables/server/server-datacenter/
    """
    raise NotImplementedError
def get_region() -> str:
    """
    A code representing the general geographic region in which the [Fastly POP] processing the
    current Compute sandbox resides.
    
    Equivalent to the "FASTLY_REGION" environment variable and to [`server.region`] in VCL, and
    has the same possible values.
    
    [`server.region`]: https://www.fastly.com/documentation/reference/vcl/variables/server/server-region/
    [Fastly POP]: https://www.fastly.com/documentation/guides/concepts/pop/
    """
    raise NotImplementedError
def get_cache_generation() -> int:
    """
    The current cache generation value for this Fastly service.
    
    The cache generation value is incremented by [purge-all operations].
    
    Equivalent to the "FASTLY_CACHE_GENERATION" environment variable and to
    [`req.vcl.generation`] in VCL.
    
    [purge-all operations]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/purging/
    [`req.vcl.generation`]: https://www.fastly.com/documentation/reference/vcl/variables/miscellaneous/req-vcl-generation/
    """
    raise NotImplementedError
def get_customer_id() -> str:
    """
    The customer ID of the Fastly customer account to which the currently executing Fastly
    service belongs.
    
    Equivalent to the "FASTLY_CUSTOMER_ID" environment variable and to [`req.customer_id`] in VCL.
    
    [`req.customer_id`]: https://www.fastly.com/documentation/reference/vcl/variables/miscellaneous/req-customer-id/
    """
    raise NotImplementedError
def get_is_staging() -> bool:
    """
    Whether the request is running in the Fastly service's [staging environment].
    
    `false` for production or `true` for staging.
    
    Equivalent to the "FASTLY_IS_STAGING" environment variable and to [`fastly.is_staging`] in VCL.
    
    [`fastly.is_staging`]: https://www.fastly.com/documentation/reference/vcl/variables/miscellaneous/fastly-is-staging/
    [staging environment]: https://docs.fastly.com/products/staging
    """
    raise NotImplementedError
def get_service_id() -> str:
    """
    The identifier for the Fastly service that is processing the current request.
    
    Equivalent to the "FASTLY_SERVICE_ID" environment variable and to [`req.service_id`] in VCL.
    
    [`req.service_id`]: https://www.fastly.com/documentation/reference/vcl/variables/miscellaneous/req-service-id/
    """
    raise NotImplementedError
def get_service_version() -> int:
    """
    The version number for the Fastly service that is processing the current request.
    
    Equivalent to the "FASTLY_SERVICE_VERSION" environment variable and to [`req.vcl.version`]
    in VCL.
    
    [`req.vcl.version`]: https://www.fastly.com/documentation/reference/vcl/variables/miscellaneous/req-vcl-version/
    """
    raise NotImplementedError
def get_namespace_id() -> str:
    """
    This function is not suitable for general-purpose use.
    """
    raise NotImplementedError
