# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Config Store] API.

[Config Store]: https://www.fastly.com/documentation/guides/concepts/edge-state/dynamic-config/#config-stores
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Store:
    """
    A Config Store.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Attempts to open the named config store.
        
        Names are case sensitive.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def get(self, key: str, max_len: int) -> Optional[str]:
        """
        Fetches a value from the config store, returning `ok(none)` if it doesn't exist.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



