# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Device detection based on the User-Agent header.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def lookup(user_agent: str, max_len: int) -> Optional[str]:
    """
    Looks up the data associated with a particular User-Agent string.
    
    Returns a list of bytes containing JSON-encoded device data. See [here] for descriptions
    of the JSON fields.
    
    [here]: https://www.fastly.com/documentation/reference/vcl/variables/client-request/client-identified/
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
