# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Compute Dictionaries] (deprecated in favor of `config-store`)

[Compute Dictionaries]: https://www.fastly.com/documentation/guides/concepts/edge-state/dynamic-config/#dictionaries
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Dictionary:
    """
    A Compute Dictionary.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens a dictionary, given its name.
        
        Names are case sensitive.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def lookup(self, key: str, max_len: int) -> Optional[str]:
        """
        Tries to look up a value in this dictionary.
        
        If the lookup is successful, this function returns `ok(some(s))` containing the found
        string `s`, or `ok(none)` if no entry with the given key was found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



