# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Edge rate limiting] API.

[Edge rate limiting]: https://docs.fastly.com/products/edge-rate-limiting
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class PenaltyBox:
    """
    A penaltybox that can be used with the edge rate limiter or
    standalone for adding and checking if some entry is in the data set.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens a `penalty-box` identified by the given name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def get_name(self) -> str:
        """
        Returns the name of this penaltybox.
        """
        raise NotImplementedError
    def add(self, entry: str, ttl: int) -> None:
        """
        Adds `entry` to a the penaltybox for the duration of ttl.
        
        Valid ttl span is 1m to 1h and TTL value is truncated to the nearest minute.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def has(self, entry: str) -> bool:
        """
        Checks if `entry` is in the penaltybox.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class RateCounter:
    """
    A rate counter that can be used with a edge rate limiter or
    standalone for counting and rate calculations.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens a `rate-counter` with the given name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def get_name(self) -> str:
        """
        Returns the name of this rate counter.
        """
        raise NotImplementedError
    def check_rate(self, entry: str, delta: int, window: int, limit: int, penalty_box: PenaltyBox, ttl: int) -> bool:
        """
        Increments an entry in a rate counter and check if the client has exceeded some average number
        of requests per second (RPS) over the window.
        
        If the client is over the rps limit for the window, add to the penaltybox for ttl. Valid ttl
        span is 1m to 1h and TTL value is truncated to the nearest minute.
        
        Returns `true` if the client is penalized (i.e. should be limited), or `false` if not.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def increment(self, entry: str, delta: int) -> None:
        """
        Increments an entry in the ratecounter by `delta`.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def lookup_rate(self, entry: str, window: int) -> int:
        """
        Looks up the current rate for entry in the ratecounter for a window.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def lookup_count(self, entry: str, duration: int) -> int:
        """
        Looks up the current count for entry in the ratecounter for duration.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



