# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Geographic data] for IP addresses.

[Geographic data]: https://www.fastly.com/blog/improve-performance-and-gain-better-end-user-intelligence-geoip-geography-detection
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types


def lookup(ip_addr: types.IpAddress, max_len: int) -> str:
    """
    Looks up the geographic data associated with a particular IP address.
    
    Returns a list of bytes containing JSON-encoded geographic data. See [here] for descriptions
    of the JSON fields.
    
    [here]: https://www.fastly.com/documentation/reference/vcl/variables/geolocation/
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
