# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
HTTP bodies.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types
from ..imports import async_io


@dataclass
class TrailerError_NotAvailableYet:
    pass


@dataclass
class TrailerError_Error:
    value: types.Error


TrailerError = Union[TrailerError_NotAvailableYet, TrailerError_Error]
"""
Trailers aren't available until the body has been completely transmitted, so this error
type can either indicate that the errors aren't available yet, or that an error occurred.
"""



def new() -> async_io.Pollable:
    """
    Creates a new empty body that can be used for outgoing requests and responses.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def append(dest: async_io.Pollable, src: async_io.Pollable) -> None:
    """
    Appends the contents of the body `src` to the body `dest`.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def read(body: async_io.Pollable, chunk_size: int) -> bytes:
    """
    Reads from a body.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def write(body: async_io.Pollable, buf: bytes) -> int:
    """
    Writes to a body.
    
    This function may write fewer bytes than requested; on success, the number of
    bytes actually written is returned.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def write_front(body: async_io.Pollable, buf: bytes) -> None:
    """
    Prepends bytes to the front of a body.
    
    On success, this function always writes all the bytes of `buf`.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close(body: async_io.Pollable) -> None:
    """
    Frees a body.
    
    This releases resources associated with the body.
    
    For streaming bodies, this is a *successful* stream termination, which will signal
    via framing that the body transfer is complete.
    
    If a handle is dropped without calling `close`, it's an *unsuccessful* stream
    termination.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def get_known_length(body: async_io.Pollable) -> Optional[int]:
    """
    Returns a `u64` body length if the length of a body is known, or `none` otherwise.
    
    If the length is unknown, it is likely due to the body arising from an HTTP/1.1 message with
    chunked encoding, an HTTP/2 or later message with no `content-length`, or being a streaming
    body.
    
    Receiving a length from this function does not guarantee that the full number of
    bytes can actually be read from the body. For example, when proxying a response from a
    backend, this length may reflect the `content-length` promised in the response, but if the
    backend connection is closed prematurely, fewer bytes may be delivered before this body
    handle can no longer be read.
    """
    raise NotImplementedError
def append_trailer(body: async_io.Pollable, name: str, value: bytes) -> None:
    """
    Adds a body trailing header with given value.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def get_trailer_names(body: async_io.Pollable, max_len: int, cursor: int) -> Tuple[str, Optional[int]]:
    """
    Gets the names of the trailers associated with this body.
    
    The first `cursor` names are skipped. The remaining names are encoded successively with
    a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
    names don't fit, the returned `option<u32>` is the index of the first name that didn't fit,
    or `none` if all the remaining names fit. If `max-len` is too small to fit any name, an
    `error.buffer-len` error is returned, providing a recommended buffer size.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_body.TrailerError)`
    """
    raise NotImplementedError
def get_trailer_value(body: async_io.Pollable, name: str, max_len: int) -> Optional[bytes]:
    """
    Gets the value for the trailer with the given name, or `none` if the trailer is not present.
    
    If there are multiple values for this header, only one is returned, which may be
    any of the values. See `get-trailer-values` if you need to get all of the values.
    
    This functions returns `ok(some(v))` if the trailer with the given name is present,
    and `ok(none)` if no trailer with the given name is present. If `max-len` is too
    small to fit the value, an `error.buffer-len` error is returned, providing a
    recommended buffer size.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_body.TrailerError)`
    """
    raise NotImplementedError
def get_trailer_values(body: async_io.Pollable, name: str, max_len: int, cursor: int) -> Tuple[bytes, Optional[int]]:
    """
    Gets multiple values associated with the trailer with the given name.
    
    As opposed to `get-trailer-value`, this function returns all of the values for this trailer.
    
    The first `cursor` values are skipped. The remaining values are encoded successively with
    a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
    values don't fit, the returned `option<u32>` is the index of the first value that didn't
    fit, or `none` if all the remaining values fit. If `max-len` is too small to fit any value,
    an `error.buffer-len` error is returned, providing a recommended buffer size.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_body.TrailerError)`
    """
    raise NotImplementedError
