# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
HTTP downstream requests and metadata.

“Downstream” here refers to incoming HTTP requests.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types
from ..imports import async_io
from ..imports import http_req

class ExtraNextRequestOptions:
    """
    Extensibility for `next-request-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class NextRequestOptions:
    """
    Configuration for `next-request`.
    """
    timeout_ms: Optional[int]
    extra: Optional[ExtraNextRequestOptions]


def next_request(options: NextRequestOptions) -> async_io.Pollable:
    """
    Prepares to accept a new downstream request.
    
    By default, each sandbox accepts a single downstream request,
    passed in as an argument to the `http-incoming.handle` call. The
    `next-request` function enables a sandbox to accept additional
    downstream requests. `next-request` returns a `pending-request`, which
    can be passed to `await-request` to wait for the request to become
    available and return the `request`.
    
    When using this function, be mindful of two considerations:
    
     - When a single sandbox accepts multiple requests, its state
       isn't automatically cleared between requests. Applications are
       therefore responsible for preventing sensitive data from leaking from
       one request to another.
    
     - There is no guarantee that a single sandbox will receive all
       requests from a given client or from a given location. When it is
       necessary to preserve state between multiple requests, store it outside
       of the sandbox.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def await_request(pending: async_io.Pollable) -> Optional[Tuple[http_req.Request, async_io.Pollable]]:
    """
    Waits until the next request is available, and then returns the resulting
    request and body.
    
    Returns `ok(none)` if there are no more requests for this sandbox.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_original_header_names(ds_request: http_req.Request, max_len: int, cursor: int) -> Tuple[str, Optional[int]]:
    """
    Returns the client request's header names exactly as they were originally received.
    
    This includes both the original header name characters' cases, as well as the original order
    of the received headers.
    
    The first `cursor` names are skipped. The remaining names are encoded successively with
    a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
    names don't fit, the returned `option<u32>` is the index of the first name that didn't fit,
    or `none` if all the remaining names fit. If `max-len` is too small to fit any name,
    an `error.buffer-len` error is returned, providing a recommended buffer size.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_original_header_count(ds_request: http_req.Request) -> int:
    """
    Returns the number of headers in the client request as originally received.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_client_ip_addr(ds_request: http_req.Request) -> Optional[types.IpAddress]:
    """
    Returns the IP address of the client making the HTTP request, if known.
    """
    raise NotImplementedError
def downstream_server_ip_addr(ds_request: http_req.Request) -> Optional[types.IpAddress]:
    """
    Returns the IP address on which this server received the HTTP request, if known.
    """
    raise NotImplementedError
def downstream_client_h2_fingerprint(ds_request: http_req.Request, max_len: int) -> str:
    """
    Gets the HTTP/2 fingerprint of client request if available.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_client_request_id(ds_request: http_req.Request, max_len: int) -> str:
    """
    Gets the id of the current request if available.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_client_oh_fingerprint(ds_request: http_req.Request, max_len: int) -> str:
    """
    Gets the fingerprint of client request headers if available.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_client_ddos_detected(ds_request: http_req.Request) -> bool:
    """
    Returns whether the request was tagged as contributing to a DDoS attack.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_cipher_openssl_name(ds_request: http_req.Request, max_len: int) -> Optional[bytes]:
    """
    Gets the cipher suite used to secure the downstream client TLS connection.
    
    The value returned will be consistent with the [OpenSSL name] for the cipher suite.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    [OpenSSL name]: https://testssl.sh/openssl-iana.mapping.html
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_protocol(ds_request: http_req.Request, max_len: int) -> Optional[bytes]:
    """
    Gets the TLS protocol version used to secure the downstream client TLS connection.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_client_hello(ds_request: http_req.Request, max_len: int) -> Optional[bytes]:
    """
    Gets the raw bytes sent by the client in the TLS ClientHello message.
    
    See [RFC 5246] for details.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    [RFC 5246]: https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_raw_client_certificate(ds_request: http_req.Request, max_len: int) -> Optional[bytes]:
    """
    Gets the raw client certificate used to secure the downstream client mTLS connection.
    
    The value returned will be based on PEM format.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_client_cert_verify_result(ds_request: http_req.Request) -> Optional[http_req.ClientCertVerifyResult]:
    """
    Returns the `client-cert-verify-result` from the downstream client mTLS handshake.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_client_servername(ds_request: http_req.Request, max_len: int) -> Optional[str]:
    """
    Returns the Server Name Indication from the downstream client TLS handshake.
    
    Returns `ok(none)` if not available.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_ja3_md5(ds_request: http_req.Request) -> Optional[bytes]:
    """
    Gets the JA3 hash of the TLS ClientHello message.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_tls_ja4(ds_request: http_req.Request, max_len: int) -> Optional[str]:
    """
    Gets the JA4 hash of the TLS ClientHello message.
    
    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def downstream_compliance_region(ds_request: http_req.Request, max_len: int) -> Optional[str]:
    """
    Gets the compliance region that the client IP address is in.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def fastly_key_is_valid(ds_request: http_req.Request) -> bool:
    """
    Returns whether or not the original client request arrived with a
    Fastly-Key belonging to a user with the rights to purge content on this
    service.
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
