# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
HTTP requests.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import http_types
from ..imports import types
from ..imports import backend
from ..imports import async_io
from ..imports import http_resp

class ExtraCacheOverrideDetails:
    """
    Extensibility for `cache-override-details`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class CacheOverrideDetails:
    """
    The fields for the `override` arm of `cache-override`.
    
    The origin response’s cache control headers will be used for ttl and
    `stale-while-revalidate` if `none`.
    """
    ttl: Optional[int]
    stale_while_revalidate: Optional[int]
    pci: bool
    surrogate_key: Optional[str]
    extra: Optional[ExtraCacheOverrideDetails]


@dataclass
class CacheOverride_None_:
    pass


@dataclass
class CacheOverride_Pass:
    pass


@dataclass
class CacheOverride_Override:
    value: CacheOverrideDetails


CacheOverride = Union[CacheOverride_None_, CacheOverride_Pass, CacheOverride_Override]
"""
Optional override for response caching behavior.
"""


class Request:
    """
    An HTTP request.
    """
    
    @classmethod
    def new(cls) -> Self:
        """
        Creates a new `request` with no method, URL, or headers, and an empty body.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_cache_override(self, cache_override: CacheOverride) -> None:
        """
        Sets the cache override behavior for this request.
        
        This setting will override any cache directive headers returned in response to this request.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_names(self, max_len: int, cursor: int) -> Tuple[str, Optional[int]]:
        """
        Reads the request's header names via a buffer of the provided size.
        
        The first `cursor` names are skipped. The remaining names are encoded successively with
        a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
        names don't fit, the returned `option<u32>` is the index of the first name that didn't fit,
        or `none` if all the remaining names fit. If `max-len` is too small to fit any name,
        an `error.buffer-len` error is returned, providing a recommended buffer size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_value(self, name: str, max_len: int) -> Optional[bytes]:
        """
        Gets the value of a header, or `none` if the header is not present.
        
        If there are multiple values for the header, only one is returned. See
        `get-header-values` if you need to get all of the values.
        
        If header name requires more than `max-len` bytes, this will return an `error.buffer-len`
        containing the required size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_values(self, name: str, max_len: int, cursor: int) -> Tuple[bytes, Optional[int]]:
        """
        Gets multiple header values for the given `name` via a buffer of the provided size.
        
        As opposed to `get-header-value`, this function returns all of the values for this header.
        
        The first `cursor` values are skipped. The remaining values are encoded successively with
        a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
        values don't fit, the returned `option<u32>` is the index of the first value that didn't
        fit, or `none` if all the remaining values fit. If `max-len` is too small to fit any value,
        an `error.buffer-len` error is returned, providing a recommended buffer size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_header_values(self, name: str, values: bytes) -> None:
        """
        Sets the values for the given header name, replacing any headers that previously existed for
        that name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def insert_header(self, name: str, value: bytes) -> None:
        """
        Sets a request header to the given value, discarding any previous values for the given
        header name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def append_header(self, name: str, value: bytes) -> None:
        """
        Adds a request header with given value.
        
        Unlike `set-header-values`, this does not discard existing values for the same header name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def remove_header(self, name: str) -> None:
        """
        Removes all request headers of the given name
        
        Returns `ok` if any headers were successfully removed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_method(self, max_len: int) -> str:
        """
        Gets the request method.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_method(self, method: str) -> None:
        """
        Sets the request method.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_uri(self, max_len: int) -> str:
        """
        Gets the request URI.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_uri(self, uri: str) -> None:
        """
        Sets the request URI.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_version(self) -> http_types.HttpVersion:
        """
        Gets the HTTP version of this request.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_version(self, version: http_types.HttpVersion) -> None:
        """
        Sets the HTTP version of this request.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_auto_decompress_response(self, encodings: http_types.ContentEncodings) -> None:
        """
        Sets the content encodings to automatically decompress responses to this request.
        
        If the response to this request is encoded by one of the encodings set by this method, the
        response will be presented to the Compute program in decompressed form with the
        `Content-Encoding` and `Content-Length` headers removed.
        
        Not all of the flags defined in `content-encodings` are supported. Currently the only
        supported flag is `content-encodings.gzip`.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def redirect_to_websocket_proxy(self, backend: backend.Backend) -> None:
        """
        Passes the WebSocket directly to a backend.
        
        This can only be used on services that have the WebSockets feature enabled and on requests
        that are valid WebSocket requests.
        
        The sending completes in the background. Once this method has been called, no other response
        can be sent to this request, and the application can exit without affecting the send.
        
        See the [WebSockets passthrough] documentation for a high-level description of this feature.
        
        [WebSockets passthrough]: https://www.fastly.com/documentation/guides/concepts/real-time-messaging/websockets-tunnel/
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_framing_headers_mode(self, mode: http_types.FramingHeadersMode) -> None:
        """
        Sets how the framing headers `Content-Length` and `Transfer-Encoding` will be determined
        when sending this request.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def redirect_to_grip_proxy(self, backend: backend.Backend) -> None:
        """
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class ClientCertVerifyResult(Enum):
    """
    TLS client certificate verified result from downstream.
    """
    OK = 0
    BAD_CERTIFICATE = 1
    CERTIFICATE_REVOKED = 2
    CERTIFICATE_EXPIRED = 3
    UNKNOWN_CA = 4
    CERTIFICATE_MISSING = 5
    CERTIFICATE_UNKNOWN = 6

@dataclass
class DnsErrorDetail:
    """
    Variant fields for `send-error.dns-error`.
    """
    rcode: Optional[int]
    info_code: Optional[int]

@dataclass
class TlsAlertReceivedDetail:
    """
    Variant fields for `send-error.tls-alert-received`.
    """
    id: Optional[int]

@dataclass
class H2ErrorDetail:
    """
    Variant fields for `send-error.h2-error`.
    """
    frame_type: int
    error_code: int

class ExtraSendErrorDetail:
    """
    Extensibility for `send-error-detail`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



@dataclass
class SendErrorDetail_DnsTimeout:
    pass


@dataclass
class SendErrorDetail_DnsError:
    value: DnsErrorDetail


@dataclass
class SendErrorDetail_DestinationNotFound:
    pass


@dataclass
class SendErrorDetail_DestinationUnavailable:
    pass


@dataclass
class SendErrorDetail_DestinationIpUnroutable:
    pass


@dataclass
class SendErrorDetail_ConnectionRefused:
    pass


@dataclass
class SendErrorDetail_ConnectionTerminated:
    pass


@dataclass
class SendErrorDetail_ConnectionTimeout:
    pass


@dataclass
class SendErrorDetail_ConnectionLimitReached:
    pass


@dataclass
class SendErrorDetail_TlsCertificateError:
    pass


@dataclass
class SendErrorDetail_TlsConfigurationError:
    pass


@dataclass
class SendErrorDetail_HttpIncompleteResponse:
    pass


@dataclass
class SendErrorDetail_HttpResponseHeaderSectionTooLarge:
    pass


@dataclass
class SendErrorDetail_HttpResponseBodyTooLarge:
    pass


@dataclass
class SendErrorDetail_HttpResponseTimeout:
    pass


@dataclass
class SendErrorDetail_HttpResponseStatusInvalid:
    pass


@dataclass
class SendErrorDetail_HttpUpgradeFailed:
    pass


@dataclass
class SendErrorDetail_HttpProtocolError:
    pass


@dataclass
class SendErrorDetail_HttpRequestCacheKeyInvalid:
    pass


@dataclass
class SendErrorDetail_HttpRequestUriInvalid:
    pass


@dataclass
class SendErrorDetail_InternalError:
    pass


@dataclass
class SendErrorDetail_TlsAlertReceived:
    value: TlsAlertReceivedDetail


@dataclass
class SendErrorDetail_TlsProtocolError:
    pass


@dataclass
class SendErrorDetail_H2Error:
    value: H2ErrorDetail


@dataclass
class SendErrorDetail_Extra:
    value: ExtraSendErrorDetail


SendErrorDetail = Union[SendErrorDetail_DnsTimeout, SendErrorDetail_DnsError, SendErrorDetail_DestinationNotFound, SendErrorDetail_DestinationUnavailable, SendErrorDetail_DestinationIpUnroutable, SendErrorDetail_ConnectionRefused, SendErrorDetail_ConnectionTerminated, SendErrorDetail_ConnectionTimeout, SendErrorDetail_ConnectionLimitReached, SendErrorDetail_TlsCertificateError, SendErrorDetail_TlsConfigurationError, SendErrorDetail_HttpIncompleteResponse, SendErrorDetail_HttpResponseHeaderSectionTooLarge, SendErrorDetail_HttpResponseBodyTooLarge, SendErrorDetail_HttpResponseTimeout, SendErrorDetail_HttpResponseStatusInvalid, SendErrorDetail_HttpUpgradeFailed, SendErrorDetail_HttpProtocolError, SendErrorDetail_HttpRequestCacheKeyInvalid, SendErrorDetail_HttpRequestUriInvalid, SendErrorDetail_InternalError, SendErrorDetail_TlsAlertReceived, SendErrorDetail_TlsProtocolError, SendErrorDetail_H2Error, SendErrorDetail_Extra]
"""
Information about errors encountered by sent requests.
"""


@dataclass
class ErrorWithDetail:
    """
    An `error` code, optionally with extra request error information.
    """
    detail: Optional[SendErrorDetail]
    error: types.Error


def send(request: Request, body: async_io.Pollable, backend: backend.Backend) -> Tuple[http_resp.Response, async_io.Pollable]:
    """
    Retrieves a response for the request, either from cache or by sending it
    to the given backend server.
    
    Returns once the response headers have been received, or an error occurs.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_req.ErrorWithDetail)`
    """
    raise NotImplementedError
def send_uncached(request: Request, body: async_io.Pollable, backend: backend.Backend) -> Tuple[http_resp.Response, async_io.Pollable]:
    """
    Sends the request directly to the backend server without performing any
    caching or inserting any cache-related headers in the response.
    
    Returns once the response headers have been received, or an error occurs.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_req.ErrorWithDetail)`
    """
    raise NotImplementedError
def send_async(request: Request, body: async_io.Pollable, backend: backend.Backend) -> async_io.Pollable:
    """
    Begins sending the request to the given backend server, and returns a
    `pending-response` that can yield the backend response or an error.
    
    This method returns as soon as the request begins sending to the backend,
    and transmission of the request body and headers will continue in the
    background.
    
    This method allows for sending more than one request at once and receiving
    their responses in arbitrary orders. See `pending-response` for more
    details on how to wait on, poll, or select between pending responses.
    
    This method is also useful for sending requests where the response is
    unimportant, but the request may take longer than the Compute program is
    able to run, as the request will continue sending even after the program
    that initiated it exits.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def send_async_uncached(request: Request, body: async_io.Pollable, backend: backend.Backend) -> async_io.Pollable:
    """
    This is to `send-async` as `send-uncached` is to `send`.
    
    As with `send-uncached`, this function sends the request directly to the
    backend server without performing any caching or inserting any
    cache-related headers in the response.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def send_async_streaming(request: Request, body: async_io.Pollable, backend: backend.Backend) -> async_io.Pollable:
    """
    Begins sending the request to the given backend server, and returns a
    `pending-response` that can yield the backend response or an error.
    
    The `body` argument is not consumed, so that it can accept further data to send.
    
    The backend connection is only closed once `http-body.close` is called. The
    `pending-response` will not yield a `response` until the body is finished.
    
    This method is most useful for programs that do some sort of processing or
    inspection of a potentially-large client request body. Streaming allows the
    program to operate on small parts of the body rather than having to read it all
    into memory at once.
    
    This method returns as soon as the request begins sending to the backend,
    and transmission of the request body and headers will continue in the
    background.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def send_async_uncached_streaming(request: Request, body: async_io.Pollable, backend: backend.Backend) -> async_io.Pollable:
    """
    This is to `send-async-streaming` as `send-uncached` is to `send`.
    
    As with `send-uncached`, this function sends the request directly to the
    backend server without performing any caching or inserting any
    cache-related headers in the response.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def await_response(pending: async_io.Pollable) -> Tuple[http_resp.Response, async_io.Pollable]:
    """
    Waits until the request is completed, and then returns the resulting
    response and body.
    
    Raises: `wit_world.types.Err(wit_world.imports.http_req.ErrorWithDetail)`
    """
    raise NotImplementedError
def close(request: Request) -> None:
    """
    Closes the `request`, releasing any associated resources.
    
    A `request` is automatically consumed when you send a request. You should call `close`
    only if you have a `request` you don't intend to use anymore.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def upgrade_websocket(backend: backend.Backend) -> None:
    """
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
