# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
HTTP responses.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import http_types
from ..imports import types
from ..imports import async_io

class KeepaliveMode(Enum):
    AUTOMATIC = 0
    NO_KEEPALIVE = 1

class Response:
    """
    An HTTP response.
    """
    
    @classmethod
    def new(cls) -> Self:
        """
        Create a new `response`.
        
        The new `response` is created with status code 200 OK, no headers, and an empty body.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_names(self, max_len: int, cursor: int) -> Tuple[str, Optional[int]]:
        """
        Read the response's header names via a buffer of the provided size.
        
        The first `cursor` names are skipped. The remaining names are encoded successively with
        a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
        names don't fit, the returned `option<u32>` is the index of the first name that didn't fit,
        or `none` if all the remaining names fit. If `max-len` is too small to fit any name,
        an `error.buffer-len` error is returned, providing a recommended buffer size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_value(self, name: str, max_len: int) -> Optional[bytes]:
        """
        Gets the value of a header, or `none` if the header is not present.
        
        If there are multiple values for the header, only one is returned. See
        `get-header-values` if you need to get all of the values.
        
        If header name requires more than `max-len` bytes, this will return an `error.buffer-len`
        containing the required size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_header_values(self, name: str, max_len: int, cursor: int) -> Tuple[bytes, Optional[int]]:
        """
        Gets multiple header values for the given `name` via a buffer of the provided size.
        
        As opposed to `get-header-value`, this function returns all of the values for this header.
        
        The first `cursor` values are skipped. The remaining values are encoded successively with
        a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
        values don't fit, the returned `option<u32>` is the index of the first value that didn't
        fit, or `none` if all the remaining values fit. If `max-len` is too small to fit any value,
        an `error.buffer-len` error is returned, providing a recommended buffer size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_header_values(self, name: str, values: bytes) -> None:
        """
        Sets the values for the given header name, replacing any headers that previously existed for
        that name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def insert_header(self, name: str, value: bytes) -> None:
        """
        Sets a response header to the given value, discarding any previous values for the given
        header name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def append_header(self, name: str, value: bytes) -> None:
        """
        Add a response header with given value.
        
        Unlike `set-header-values`, this does not discard existing values for the same header name.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def remove_header(self, name: str) -> None:
        """
        Remove all response headers of the given name
        
        Returns `ok` if any headers were successfully removed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_version(self) -> http_types.HttpVersion:
        """
        Gets the HTTP version of this response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_version(self, version: http_types.HttpVersion) -> None:
        """
        Sets the HTTP version of this response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_status(self) -> int:
        """
        Gets the HTTP status code of the response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_status(self, status: int) -> None:
        """
        Sets the HTTP status code of the response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_framing_headers_mode(self, mode: http_types.FramingHeadersMode) -> None:
        """
        Sets how the framing headers `Content-Length` and `Transfer-Encoding` will be determined
        when sending this response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def set_http_keepalive_mode(self, mode: KeepaliveMode) -> None:
        """
        Adjust the response's connection reuse mode.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_remote_ip_addr(self) -> Optional[types.IpAddress]:
        """
        Gets the destination IP address used for this response, if known.
        """
        raise NotImplementedError
    def get_remote_port(self) -> Optional[int]:
        """
        Gets the destination port used for this response, if known.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def send_downstream(response: Response, body: async_io.Pollable) -> None:
    """
    Sends a response to the client that made the request passed to `http-incoming.handle`.
    
    This method returns as soon as the response header begins sending to the client, and
    transmission of the response will continue in the background.
    
    Data for the body must be written before calling this function. To start a response
    and write data to it afterwards, use `send-downstream-streaming` instead.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def send_downstream_streaming(response: Response, body: async_io.Pollable) -> None:
    """
    Starts a response to the client that made the request passed to `http-incoming.handle`.
    
    The body is left open, allowing data to be written after calling this function.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close(response: Response) -> None:
    """
    Closes the `response`, releasing any associated resources.
    
    A `response` is consumed when you send a response to a client or stream one to a
    client. You should call `close` only if you have a `response` you don't intend
    to use anymore.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
