# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Types used by HTTP interfaces in this package.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class HttpVersion(Enum):
    """
    HTTP protocol versions.
    """
    HTTP09 = 0
    HTTP10 = 1
    HTTP11 = 2
    H2 = 3
    H3 = 4

class ContentEncodings(Flag):
    """
    HTTP [content encoding] flags
    
    The names of these flags correspond to
    [IANA HTTP Content Coding Registry] names.
    
    Not all of these content encoding flags are supported in all APIs that
    use this `content-encodings` type. See the documentation for individual
    functions for details.
    
    [content encoding]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-encoding
    [IANA HTTP Content Coding Registry]: https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding
    """
    GZIP = auto()
    BR = auto()
    ZSTD = auto()
    DCB = auto()
    DCZ = auto()
    AES128GCM = auto()

class FramingHeadersMode(Enum):
    """
    Determines how the framing headers (`Content-Length`/`Transfer-Encoding`) are set for a
    request or response.
    """
    AUTOMATIC = 0
    MANUALLY_FROM_HEADERS = 1


