# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[HTTP Cache] API.

Overall, this should look very familiar to users of the Core Cache API. The primary differences
are:

- HTTP `request`s and `response`s are used rather than relying on the user to
  encode headers, status codes, etc in `user-metadata`.

- Convenience functions specific to HTTP semantics are provided, such as `is-request-cacheable`,
  `get-suggested-backend-request`, `get-suggested-write-options`, and
  `transaction-record-not-cacheable`.

The HTTP-specific behavior of these functions is intended to support applications that match the
normative guidance in [RFC 9111]. For example, `is-request-cacheable` returns `false` for `POST`
requests. However, this answer along with those of many of these functions explicitly provide
*suggestions*; they do not necessarily need to be followed if custom behavior is required, such
as caching `POST` responses when the application author knows that to be safe.

The starting points for this API are `lookup` (no request collapsing) and `transaction-lookup`
(request collapsing).

[HTTP Cache]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/cache-freshness/
[RFC 9111]: https://www.rfc-editor.org/rfc/rfc9111.html
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import cache
from ..imports import http_req
from ..imports import backend
from ..imports import http_resp
from ..imports import async_io

class ExtraLookupOptions:
    """
    Extensibility for `lookup-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class LookupOptions:
    """
    Non-required options for cache lookups.
    """
    override_key: Optional[bytes]
    backend: Optional[backend.Backend]
    extra: Optional[ExtraLookupOptions]

class ExtraWriteOptions:
    """
    Extensibility for `write-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class WriteOptions:
    """
    Options for cache insertions and updates.
    """
    max_age_ns: int
    vary_rule: Optional[str]
    initial_age_ns: Optional[int]
    stale_while_revalidate_ns: Optional[int]
    stale_if_error_ns: Optional[int]
    surrogate_keys: Optional[str]
    length: Optional[int]
    sensitive_data: bool
    extra: Optional[ExtraWriteOptions]

class SuggestedWriteOptions:
    """
    The methods in this resource return values that correspond to the fields in a
    `write-options`. This type is used when a `write-options` value would
    be returned, so that it can use `max-len` parameters when returning
    dynamically-sized data, and so that it excludes the `extra` field, since borrowed
    handles cannot be returned from functions.
    """
    
    def get_max_age_ns(self) -> int:
        """
        Returns the suggested value for the `write-options.max-age-ns` field.
        """
        raise NotImplementedError
    def get_vary_rule(self, max_len: int) -> str:
        """
        Returns the suggested value for the `write-options.vary-rule` field.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_initial_age_ns(self) -> int:
        """
        Returns the suggested value for the `write-options.initial-age-ns` field.
        """
        raise NotImplementedError
    def get_stale_while_revalidate_ns(self) -> int:
        """
        Returns the suggested value for the `write-options.stale-while-revalidate-ns` field.
        """
        raise NotImplementedError
    def get_surrogate_keys(self, max_len: int) -> str:
        """
        Returns the suggested value for the `write-options.surrogate-keys` field.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_length(self) -> Optional[int]:
        """
        Returns the suggested value for the `write-options.length` field.
        """
        raise NotImplementedError
    def get_sensitive_data(self) -> bool:
        """
        Returns the suggested value for the `write-options.sensitive-data` field.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class StorageAction(Enum):
    """
    The suggested action to take for spec-recommended behavior following
    `prepare-response-for-storage`.
    """
    INSERT = 0
    UPDATE = 1
    DO_NOT_STORE = 2
    RECORD_UNCACHEABLE = 3

class Entry:
    """
    An HTTP Cache transaction.
    """
    
    @classmethod
    def transaction_lookup(cls, req_handle: http_req.Request, options: LookupOptions) -> Self:
        """
        Performs a cache lookup based on the given request.
        
        This operation always participates in request collapsing and may return an obligation to
        insert or update responses, and/or stale responses.
        
        The request is not consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_insert(self, resp_handle: http_resp.Response, options: WriteOptions) -> async_io.Pollable:
        """
        Inserts a response into the cache with the given options, returning a streaming body handle
        that is ready for writing or appending.
        
        Can only be used if the cache handle state includes the `must-insert-or-update` flag.
        
        The response is consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_insert_and_stream_back(self, resp_handle: http_resp.Response, options: WriteOptions) -> Tuple[async_io.Pollable, Self]:
        """
        Inserts a response into the cache with the given options, and return a fresh cache handle
        that can be used to retrieve and stream the response while it's being inserted.
        
        This helps avoid the “slow reader” problem on a teed stream, for example when a program
        wishes to store a backend request in the cache while simultaneously streaming to a client
        in an HTTP response.
        
        The response is consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_update(self, resp_handle: http_resp.Response, options: WriteOptions) -> None:
        """
        Updates freshness lifetime, response headers, and caching settings without updating the
        response body.
        
        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must-insert-or-update`
        
        The response is consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_update_and_return_fresh(self, resp_handle: http_resp.Response, options: WriteOptions) -> Self:
        """
        Updates freshness lifetime, response headers, and caching settings without updating the
        response body, and return a fresh cache handle that can be used to retrieve and stream the
        stored response.
        
        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must-insert-or-update`
        
        The response is consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_record_not_cacheable(self, options: WriteOptions) -> None:
        """
        Disables request collapsing and response caching for this cache entry.
        
        In Varnish terms, this function stores a hit-for-pass object.
        
        Only the max age and, optionally, the vary rule are read from the `options`
        for this function.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_suggested_backend_request(self) -> http_req.Request:
        """
        Prepares a suggested request to make to a backend to satisfy the looked-up request.
        
        If there is a stored, stale response, this suggested request may be for revalidation. If the
        looked-up request is ranged, the suggested request will be unranged in order to try caching
        the entire response.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_suggested_write_options(self, response: http_resp.Response) -> SuggestedWriteOptions:
        """
        Prepares a suggested set of cache write options for a given request and response pair.
        
        The response is not consumed.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def prepare_response_for_storage(self, response: http_resp.Response) -> Tuple[StorageAction, http_resp.Response]:
        """
        Adjusts a response into the appropriate form for storage and provides a storage action
        recommendation.
        
        For example, if the looked-up request contains conditional headers, this function will
        interpret a `304 Not Modified` response for revalidation by updating headers.
        
        In addition to the updated response, this function returns the recommended storage action.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_found_response(self, transform_for_client: int) -> Optional[Tuple[http_resp.Response, async_io.Pollable]]:
        """
        Retrieves a stored response from the cache, returning `ok(none)` if
        there was no response found.
        
        If `transform-for-client` is set, the response will be adjusted according to the looked-up
        request. For example, a response retrieved for a range request may be transformed into a
        `206 Partial Content` response with an appropriate `content-range` header.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_state(self) -> cache.LookupState:
        """
        Gets the state of a cache transaction.
        
        Primarily useful after performing the lookup to determine what subsequent operations are
        possible and whether any insertion or update obligations exist.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_length(self) -> Optional[int]:
        """
        Gets the length of the found response, returning `ok(none)` if there
        was no response found or no length was provided.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_max_age_ns(self) -> Optional[int]:
        """
        Gets the configured max age of the found response in nanoseconds, returning `ok(none)`
        if there was no response found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_stale_while_revalidate_ns(self) -> Optional[int]:
        """
        Gets the configured stale-while-revalidate period of the found response in nanoseconds,
        returning `ok(none)` if there was no response found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_age_ns(self) -> Optional[int]:
        """
        Gets the age of the found response in nanoseconds, returning `ok(none)`
        if there was no response found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_hits(self) -> Optional[int]:
        """
        Gets the number of cache hits for the found response, returning `ok(none)`
        if there was no response found.
        
        This figure only reflects hits for a stored response in a particular cache server
        or cluster, not the entire Fastly network.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_sensitive_data(self) -> Optional[bool]:
        """
        Gets whether a found response is marked as containing sensitive data, returning `ok(none)`
        if there was no response found.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_surrogate_keys(self, max_len: int) -> Optional[str]:
        """
        Gets the surrogate keys of the found response, returning `ok(none)` if
        there was no response found.
        
        The output is a list of surrogate keys separated by spaces.
        
        If the full list requires more than `max-len` bytes, an `error.buffer-len`
        error is returned containing the required size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def get_vary_rule(self, max_len: int) -> Optional[str]:
        """
        Gets the vary rule of the found response, returning `ok(none)` if there
        was no response found.
        
        The output is a list of header names separated by spaces.
        
        If the full list requires more than `max-len` bytes, an `error.buffer-len`
        error is returned containing the required size.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def transaction_abandon(self) -> None:
        """
        Abandons an obligation to provide a response to the cache.
        
        Useful if there is an error before streaming is possible, for example if a backend is
        unreachable.
        
        If there are other requests collapsed on this transaction, one of those other requests will
        be awoken and given the obligation to provide a response. If subsequent requests
        are unlikely to yield cacheable responses, this may lead to undesired serialization of
        requests. Consider using `transaction-record-not-cacheable` to make lookups for this request
        bypass the cache.
        
        Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def is_request_cacheable(request: http_req.Request) -> bool:
    """
    Determines whether a request is cacheable per conservative [RFC 9111] semantics.
    
    In particular, this function checks whether the request method is `GET` or `HEAD`, and
    considers requests with other methods uncacheable. Applications where it is safe to cache
    responses to other methods should consider using their own cacheability check instead of
    this function.
    
    [RFC 9111]: https://www.rfc-editor.org/rfc/rfc9111.html
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def get_suggested_cache_key(request: http_req.Request, max_len: int) -> bytes:
    """
    Retrieves the default cache key for the request.
    
    If the full key requires more than `max-len` bytes, an `error.buffer-len`
    error is returned containing the required size.
    
    At the moment, HTTP cache keys must always be 32 bytes.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def close_entry(handle: Entry) -> None:
    """
    Closes an ongoing interaction with the cache.
    
    If the cache handle state includes `must-insert-or-update` (and hence no insert or update
    has been performed), closing the handle cancels any request collapsing, potentially choosing
    a new waiter to perform the insertion/update.
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
