# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Image Optimizer] API.

[Image Optimizer]: https://www.fastly.com/documentation/guides/full-site-delivery/image-optimization/about-fastly-image-optimizer/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import backend
from ..imports import async_io
from ..imports import http_resp
from ..imports import http_req

class ExtraImageOptimizerTransformOptions:
    """
    Extensibility for `image-optimizer-transform-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class ImageOptimizerTransformOptions:
    sdk_claims_opts: Optional[str]
    extra: Optional[ExtraImageOptimizerTransformOptions]


def transform_image_optimizer_request(origin_image_request: http_req.Request, origin_image_request_body: Optional[async_io.Pollable], origin_image_request_backend: backend.Backend, io_transform_options: ImageOptimizerTransformOptions) -> Tuple[http_resp.Response, async_io.Pollable]:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
