# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Interface to Fastly's [Compute KV Store].

For a high-level introduction to this feature, see this [blog post].

[Compute KV Store]: https://www.fastly.com/documentation/guides/concepts/edge-state/data-stores/#kv-stores
[blog post]: https://www.fastly.com/blog/introducing-the-compute-edge-kv-store-global-persistent-storage-for-compute-functions
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import async_io

class Entry:
    """
    A response from a KV Store Lookup operation.
    
    This type holds the `body`, metadata, and generation of found key.
    """
    
    def take_body(self) -> Optional[async_io.Pollable]:
        """
        Take and return the body from this `entry`, if it has one; otherwise return `none`.
        
        After calling this method, this entry will no longer have a body.
        """
        raise NotImplementedError
    def metadata(self, max_len: int) -> Optional[str]:
        """
        Read the metadata of the KV Store item, if present.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def generation(self) -> int:
        """
        Read the current generation of the KV Store item.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class ExtraKvError:
    """
    Extensibility for `kv-error`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



@dataclass
class KvError_BadRequest:
    pass


@dataclass
class KvError_PreconditionFailed:
    pass


@dataclass
class KvError_PayloadTooLarge:
    pass


@dataclass
class KvError_InternalError:
    pass


@dataclass
class KvError_TooManyRequests:
    pass


@dataclass
class KvError_GenericError:
    pass


@dataclass
class KvError_Extra:
    value: ExtraKvError


KvError = Union[KvError_BadRequest, KvError_PreconditionFailed, KvError_PayloadTooLarge, KvError_InternalError, KvError_TooManyRequests, KvError_GenericError, KvError_Extra]
"""
A value indicating the status of a KV store operation.
"""


class InsertMode(Enum):
    """
    Selects the behavior for an insert when the new key matches an existing key.
    
    A KV store maintains the property that its keys are unique from each other. If an insert
    has a key that doesn't match any key already in the store, then the pair of the key and the
    new value is inserted into the store. However, if the insert's key does match a key already
    in the store, then no new key-value pair is inserted, and the insert's `insert-mode.mode`
    determines what it does instead.
    """
    OVERWRITE = 0
    ADD = 1
    APPEND = 2
    PREPEND = 3

class ExtraInsertOptions:
    """
    Extensibility for `insert-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class InsertOptions:
    """
    Options for configuring the behavior of the `insert` function.
    """
    background_fetch: bool
    if_generation_match: Optional[int]
    metadata: Optional[str]
    time_to_live_sec: Optional[int]
    mode: InsertMode
    extra: Optional[ExtraInsertOptions]

class ListMode(Enum):
    """
    Modes of KV Store list operations.
    
    This type serves to facilitate alternative methods of cache interactions with list operations.
    """
    STRONG = 0
    EVENTUAL = 1

class ExtraListOptions:
    """
    Extensibility for `list-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class ListOptions:
    """
    Options for `list` and `list-async`.
    """
    mode: ListMode
    cursor: Optional[str]
    limit: Optional[int]
    prefix: Optional[str]
    extra: Optional[ExtraListOptions]

class Store:
    """
    A KV Store.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens the KV Store with the given name.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def lookup(self, key: str) -> Optional[Entry]:
        """
        Looks up a value in the KV Store.
        
        Returns `ok(some(v))` with the value `v` that was found, `ok(none)` if no value was
        found, or `err(e)` indicating the error `e` occurred.
        
        This function waits until the operation completes.
        
        Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
        """
        raise NotImplementedError
    def lookup_async(self, key: str) -> async_io.Pollable:
        """
        Look up a value in the KV Store asynchronously.
        
        This function initiates an async lookup of a value in the KV Store. Use
        `await-lookup` to finish the lookup.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def insert(self, key: str, body: async_io.Pollable, options: InsertOptions) -> None:
        """
        Inserts a value into the KV Store.
        
        If the KV Store already contains a value for this key, the `mode` field
        of the `options` argument specifies how the existing value is handled.
        
        This function waits until the operation completes.
        
        Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
        """
        raise NotImplementedError
    def insert_async(self, key: str, body: async_io.Pollable, options: InsertOptions) -> async_io.Pollable:
        """
        Insert a value into the KV Store asynchronously.
        
        If the KV Store already contains a value for this key, the `mode` field
        of the `options` argument specifies how the existing value is handled.
        
        This function initiates an async insert of a value in the KV Store. Use
        `await-insert` to finish the lookup.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def delete(self, key: str) -> bool:
        """
        Deletes a value in the KV Store.
        
        Returns `ok(true)` if a value was successfully deleted, `ok(false)` if no value was
        found, or `err(e)` indicating the error `e` occurred.
        
        This function waits until the operation completes.
        
        Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
        """
        raise NotImplementedError
    def delete_async(self, key: str) -> async_io.Pollable:
        """
        Delete of a value in the KV Store.
        
        This function initiates an async delete of a value in the KV Store. Use
        `await-delete` to finish the lookup.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def list(self, options: ListOptions) -> async_io.Pollable:
        """
        Lists keys in the KV Store.
        
        Returns `ok(b)` with the body `b` on success, or `err(e)` indicating the error `e`
        occurred.
        
        This function waits until the operation completes.
        
        Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
        """
        raise NotImplementedError
    def list_async(self, options: ListOptions) -> async_io.Pollable:
        """
        List of keys in the KV Store.
        
        This function initiates an async list value in the KV Store. Use
        `await-list` to finish the lookup.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def await_lookup(handle: async_io.Pollable) -> Optional[Entry]:
    """
    Wait on the async lookup of a value in the KV Store.
    
    Returns `ok(some(v))` with the value `v` that was found, `ok(none)` if no value was
    found, or `err(e)` indicating the error `e` occurred.
    
    Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
    """
    raise NotImplementedError
def await_insert(handle: async_io.Pollable) -> None:
    """
    Wait on the async insert of a value in the KV Store.
    
    Returns `ok` if the `insert` succeeded, or an error code on failure.
    
    Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
    """
    raise NotImplementedError
def await_delete(handle: async_io.Pollable) -> bool:
    """
    Wait on the async delete of a value in the KV Store.
    
    Returns `ok(true)` if a value was successfully deleted, `ok(false)` if no value was
    found, or `err(e)` indicating the error `e` occurred.
    
    Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
    """
    raise NotImplementedError
def await_list(handle: async_io.Pollable) -> async_io.Pollable:
    """
    Wait on the async list of keys in the KV Store.
    
    Returns `ok(b)` with the JSON-encoded body `b` on success, or `err(e)` indicating
    the error `e` occurred.
    
    Raises: `componentize_py_types.Err(wit_world.imports.kv_store.KvError)`
    """
    raise NotImplementedError
