# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Low-level interface to Fastly's [Real-Time Log Streaming] endpoints.

[Real-Time Log Streaming]: https://docs.fastly.com/en/guides/about-fastlys-realtime-log-streaming-features
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Endpoint:
    """
    A logging endpoint.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Tries to get an endpoint by name.
        
        Currently, the conditions on an endpoint name are:
        - It must not be empty.
        - It must not contain newlines (`\n`) or colons (`:`).
        - It must not be `stdout` or `stderr`, which are reserved for debugging.
        
        Names are case sensitive. Calling `get-endpoint` with a name that doesn't correspond to any
        logging endpoint available in your service will still return a usable endpoint, and writes
        to that endpoint will succeed. Refer to your service dashboard to diagnose missing log
        events.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def write(self, msg: bytes) -> None:
        """
        Writes a data to the given endpoint.
        
        Each call to `write` with a non-empty message produces a single log event.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



