# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Cache Purging] API.

[Cache Purging]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/purging/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class ExtraPurgeOptions:
    """
    Extensibility for `purge-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class PurgeOptions:
    soft_purge: bool
    extra: Optional[ExtraPurgeOptions]


def purge_surrogate_key(surrogate_keys: str, purge_options: PurgeOptions) -> None:
    """
    Purge a surrogate key for the current service.
    
    A surrogate key can be a max of 1024 characters.
    A surrogate key must contain only printable ASCII characters (those between `0x21` and `0x7E`,
    inclusive).
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def purge_surrogate_key_verbose(surrogate_keys: str, purge_options: PurgeOptions, max_len: int) -> str:
    """
    Purge a surrogate key for the current service, and return the purge id.
    
    This is similar to `purge-surrogate-key`, but on success, returns a
    [JSON purge response] containing an ASCII alphanumeric string identifying
    a purging.
    
    [JSON purge response]: https://developer.fastly.com/reference/api/purging/#purge-tag
    
    Raises: `wit_world.types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
