# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Secret Store] API.

[Secret Store]: https://www.fastly.com/documentation/reference/api/services/resources/secret-store/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Secret:
    """
    An individual secret.
    """
    
    @classmethod
    def from_bytes(cls, bytes: bytes) -> Self:
        """
        Creates a new “secret” from the given memory.
        
        This is *not* the suggested way to create `secret`s; instead, we suggest using `get`.
        This secret will *NOT* be shared with other sandboxes.
        
        This method can be used for data that should be secret, but is being obtained by
        some other means than the secret store. New “secrets” created this way use plaintext
        only, and live in the sandbox's memory unencrypted for much longer than secrets
        generated by `get`. They should thus only be used in situations in which an API requires
        a `secret`, but you cannot (for whatever reason) use a `store` to store them.
        
        As the early note says, this `secret` will be local to the current sandbox, and
        will not be shared with other instances of this service.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def plaintext(self, max_len: int) -> bytes:
        """
        Returns the plaintext value of this secret.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Store:
    """
    A Secret Store.
    """
    
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens the Secret Store with the given name.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.OpenError)`
        """
        raise NotImplementedError
    def get(self, key: str) -> Optional[Secret]:
        """
        Tries to look up a Secret by name in this secret store.
        
        If successful, this method returns `ok(some(s))` containing the found secret `s` if the
        secret is found, or `ok(none)` if the secret was not found.
        
        Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



