# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Fastly Next-Gen WAF] API.

[Fastly Next-Gen WAF]: https://docs.fastly.com/en/ngwaf/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types
from ..imports import async_io
from ..imports import http_req

class ExtraInspectOptions:
    """
    Extensibility for `inspect-options`
    """
    
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


@dataclass
class InspectOptions:
    """
    Configuration for inspecting a `request` using Security.
    """
    corp: Optional[str]
    workspace: Optional[str]
    override_client_ip: Optional[types.IpAddress]
    extra: Optional[ExtraInspectOptions]


def inspect(request: http_req.Request, body: async_io.Pollable, options: InspectOptions, max_len: int) -> str:
    """
    Inspects request HTTP traffic using the [NGWAF] lookaside service.
    
    Returns a JSON-encoded string.
    
    [NGWAF]: https://docs.fastly.com/en/ngwaf/
    
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
