# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
[Shielding] API.

[Shielding]: https://www.fastly.com/documentation/guides/concepts/shielding/
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import backend

class ShieldBackendOptions:
    """
    Options for `backend-for-shield`.
    """
    
    def __init__(self) -> None:
        raise NotImplementedError

    def set_cache_key(self, cache_key: str) -> None:
        raise NotImplementedError
    def set_first_byte_timeout(self, timeout_ms: int) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



def shield_info(name: str, max_len: int) -> str:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
def backend_for_shield(name: str, options: Optional[ShieldBackendOptions]) -> backend.Backend:
    """
    Raises: `componentize_py_types.Err(wit_world.imports.types.Error)`
    """
    raise NotImplementedError
