# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Types used by many interfaces in this package.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



@dataclass
class Error_GenericError:
    pass


@dataclass
class Error_InvalidArgument:
    pass


@dataclass
class Error_AuxiliaryError:
    pass


@dataclass
class Error_BufferLen:
    value: int


@dataclass
class Error_Unsupported:
    pass


@dataclass
class Error_HttpInvalid:
    pass


@dataclass
class Error_HttpUser:
    pass


@dataclass
class Error_HttpIncomplete:
    pass


@dataclass
class Error_CannotRead:
    pass


@dataclass
class Error_HttpHeadTooLarge:
    pass


@dataclass
class Error_HttpInvalidStatus:
    pass


@dataclass
class Error_LimitExceeded:
    pass


Error = Union[Error_GenericError, Error_InvalidArgument, Error_AuxiliaryError, Error_BufferLen, Error_Unsupported, Error_HttpInvalid, Error_HttpUser, Error_HttpIncomplete, Error_CannotRead, Error_HttpHeadTooLarge, Error_HttpInvalidStatus, Error_LimitExceeded]
"""
A common error type used by many functions in this package.

TODO: In the future this should be split up into more-specific error
enums so that it better documents which errors each function can actually
return and what they mean.
"""


class OpenError(Enum):
    """
    An error returned by `open`-like functions.
    """
    INVALID_SYNTAX = 0
    NAME_TOO_LONG = 1
    RESERVED = 2
    NOT_FOUND = 3
    UNSUPPORTED = 4
    LIMIT_EXCEEDED = 5
    GENERIC_ERROR = 6


@dataclass
class IpAddress_Ipv4:
    value: Tuple[int, int, int, int]


@dataclass
class IpAddress_Ipv6:
    value: Tuple[int, int, int, int, int, int, int, int]


IpAddress = Union[IpAddress_Ipv4, IpAddress_Ipv6]
"""
IPv4 or IPv6 addresses.
"""



