# This file is automatically generated by generate_patches.
# It is not intended for manual editing.
"""Errors returned on ACL lookup failure."""

from fastly_compute.exceptions import FastlyError


class AclError(FastlyError):
    """Errors returned on ACL lookup failure."""


class TooManyRequests(AclError):
    """Too many requests have been made.

    This corresponds to an HTTP error code of 429, “Too Many Requests”.
    """


class GenericError(AclError):
    """Generic error value.

    This means that some unexpected error occurred.
    """
