# This file is automatically generated by scripts/generate_exceptions.
# It is not intended for manual editing.
"""An `error` code, optionally with extra request error information."""

from fastly_compute.exceptions import FastlyError


class ErrorWithDetail(FastlyError):
    """An `error` code, optionally with extra request error information."""
