# This file is automatically generated by scripts/generate_exceptions.
# It is not intended for manual editing.
"""A value indicating the status of a KV store operation."""

from fastly_compute.exceptions import FastlyError


class KvError(FastlyError):
    """A value indicating the status of a KV store operation."""


class BadRequest(KvError):
    """KV store cannot or will not process the request due to something that is perceived to be a
    client error.

    This will map to the api's 400 codes.
    """


class PreconditionFailed(KvError):
    """KV store cannot fulfill the request, as defined by the client's prerequisites, for example
    `if-generation-match`.

    This will map to the api's 412 codes.
    """


class PayloadTooLarge(KvError):
    """The size limit for a KV store key was exceeded.

    This will map to the api's 413 codes.
    """


class InternalError(KvError):
    """The system encountered an unexpected internal error.

    This will map to all remaining http error codes.
    """


class TooManyRequests(KvError):
    """Too many requests have been made to the KV store.

    This will map to the api's 429 codes.
    """


class GenericError(KvError):
    """Generic error value.

    This means that some unexpected error occurred.
    """


class Extra(KvError):
    """Additional error information may be added in the future via this resource type."""
