"""Decorator and error mappings for remapping WIT Err values to SDK exceptions.

This module is part of the generated binding layer and is only imported
when running inside the Wasm sandbox or under Viceroy, where wit_world and
componentize_py_types are available.
"""

from collections.abc import Callable, Mapping
from enum import Enum
from functools import wraps
from typing import Any

import wit_world.imports.acl
import wit_world.imports.http_body
import wit_world.imports.http_req
import wit_world.imports.kv_store
import wit_world.imports.types
from componentize_py_types import Err

import fastly_compute.exceptions.acl.acl_error
import fastly_compute.exceptions.http_body.trailer_error
import fastly_compute.exceptions.http_req
import fastly_compute.exceptions.kv_store.kv_error
import fastly_compute.exceptions.types.error
import fastly_compute.exceptions.types.open_error
from fastly_compute.exceptions import FastlyError, UnexpectedFastlyError


def remap_wit_errors(
    idiomatic_exceptions: Mapping[Any, type[FastlyError]] | None = None,
) -> Callable:
    """Raise more idiomatic exceptions from a function that returns a WIT ``result``.

    A ``result``'s error case is always wrapped in a generic ``Err`` exception by
    componentize-py.  This decorator converts that to a more descriptive exception
    that can be selectively caught.

    :arg idiomatic_exceptions: A map of the types of WIT-level ``Err.value``s to
        more informative exception classes.  These classes receive the ``Err.value``
        as a constructor argument.  If the value's type is not found in the map the
        error is wrapped in ``UnexpectedFastlyError``.

        Enum members may also be used as mapping keys.  Exceptions raised from those
        receive no constructor arguments, since enum member values are generated and
        carry no user-meaningful information.
    """
    if idiomatic_exceptions is None:
        idiomatic_exceptions = {}

    def decorator(func: Callable) -> Callable:
        @wraps(func)
        def wrapper(*args, **kwargs):
            try:
                return func(*args, **kwargs)
            except Err as e:
                error_value = e.value
                if isinstance(error_value, Enum):
                    key = error_value
                    exc_args = ()
                else:
                    key = type(error_value)
                    exc_args = (error_value,)
                idiomatic_exception = idiomatic_exceptions.get(
                    key, UnexpectedFastlyError
                )
                raise idiomatic_exception(*exc_args) from e

        return wrapper

    return decorator


# MAPPINGS is generated by scripts/generate_bindings -- do not edit
MAPPINGS: Mapping[Any, type[FastlyError]] = {
    wit_world.imports.acl.AclError.GENERIC_ERROR: fastly_compute.exceptions.acl.acl_error.GenericError,
    wit_world.imports.acl.AclError.TOO_MANY_REQUESTS: fastly_compute.exceptions.acl.acl_error.TooManyRequests,
    wit_world.imports.http_body.TrailerError_Error: fastly_compute.exceptions.http_body.trailer_error.Error,
    wit_world.imports.http_body.TrailerError_NotAvailableYet: fastly_compute.exceptions.http_body.trailer_error.NotAvailableYet,
    wit_world.imports.http_req.ErrorWithDetail: fastly_compute.exceptions.http_req.ErrorWithDetail,
    wit_world.imports.kv_store.KvError_BadRequest: fastly_compute.exceptions.kv_store.kv_error.BadRequest,
    wit_world.imports.kv_store.KvError_Extra: fastly_compute.exceptions.kv_store.kv_error.Extra,
    wit_world.imports.kv_store.KvError_GenericError: fastly_compute.exceptions.kv_store.kv_error.GenericError,
    wit_world.imports.kv_store.KvError_InternalError: fastly_compute.exceptions.kv_store.kv_error.InternalError,
    wit_world.imports.kv_store.KvError_PayloadTooLarge: fastly_compute.exceptions.kv_store.kv_error.PayloadTooLarge,
    wit_world.imports.kv_store.KvError_PreconditionFailed: fastly_compute.exceptions.kv_store.kv_error.PreconditionFailed,
    wit_world.imports.kv_store.KvError_TooManyRequests: fastly_compute.exceptions.kv_store.kv_error.TooManyRequests,
    wit_world.imports.types.Error_AuxiliaryError: fastly_compute.exceptions.types.error.AuxiliaryError,
    wit_world.imports.types.Error_BufferLen: fastly_compute.exceptions.types.error.BufferLen,
    wit_world.imports.types.Error_CannotRead: fastly_compute.exceptions.types.error.CannotRead,
    wit_world.imports.types.Error_GenericError: fastly_compute.exceptions.types.error.GenericError,
    wit_world.imports.types.Error_HttpHeadTooLarge: fastly_compute.exceptions.types.error.HttpHeadTooLarge,
    wit_world.imports.types.Error_HttpIncomplete: fastly_compute.exceptions.types.error.HttpIncomplete,
    wit_world.imports.types.Error_HttpInvalid: fastly_compute.exceptions.types.error.HttpInvalid,
    wit_world.imports.types.Error_HttpInvalidStatus: fastly_compute.exceptions.types.error.HttpInvalidStatus,
    wit_world.imports.types.Error_HttpUser: fastly_compute.exceptions.types.error.HttpUser,
    wit_world.imports.types.Error_InvalidArgument: fastly_compute.exceptions.types.error.InvalidArgument,
    wit_world.imports.types.Error_LimitExceeded: fastly_compute.exceptions.types.error.LimitExceeded,
    wit_world.imports.types.Error_Unsupported: fastly_compute.exceptions.types.error.Unsupported,
    wit_world.imports.types.OpenError.GENERIC_ERROR: fastly_compute.exceptions.types.open_error.GenericError,
    wit_world.imports.types.OpenError.INVALID_SYNTAX: fastly_compute.exceptions.types.open_error.InvalidSyntax,
    wit_world.imports.types.OpenError.LIMIT_EXCEEDED: fastly_compute.exceptions.types.open_error.LimitExceeded,
    wit_world.imports.types.OpenError.NAME_TOO_LONG: fastly_compute.exceptions.types.open_error.NameTooLong,
    wit_world.imports.types.OpenError.NOT_FOUND: fastly_compute.exceptions.types.open_error.NotFound,
    wit_world.imports.types.OpenError.RESERVED: fastly_compute.exceptions.types.open_error.Reserved,
    wit_world.imports.types.OpenError.UNSUPPORTED: fastly_compute.exceptions.types.open_error.Unsupported,
    type(None): fastly_compute.exceptions.FastlyError,
}
