# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import http_req
from ..imports import async_io

class HttpIncoming(Protocol):

    @abstractmethod
    def handle(self, request: http_req.Request, body: async_io.Pollable) -> None:
        """
        Handle the given request.
        
        This function is called once per sandbox. When it returns, the
        sandbox exits. To opt into receiving multiple requests in a single
        sandbox, use `http-downstream.next-request`.
        
        To send a response for the given `request`, use `send-downstream`, or to
        stream the response body after the response has been initiated, use
        `send-downstream-streaming`.
        
        Raises: `wit_world.types.Err(None)`
        """
        raise NotImplementedError


