# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The exported interface.

The `handle` function serves as the main entrypoint to applications. Unlike the
rest of the interfaces in this package, this `http-incoming` interface is exported by
applications rather than imported, which means that this is a function defined
by the application and called from the outside, rather than a function called
by the application into the outside.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


