# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""Blocklists using [Access Control Lists] (ACLs)

[Access Control Lists]: https://www.fastly.com/documentation/reference/api/acls/
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import acl as _wit
from wit_world.imports.types import IpAddress

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Acl",
    "IpAddress",
]




class Acl(FastlyResource[_wit.Acl]):
    """An ACL."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens an ACL linked to the current service with the given link name."""
        return cls(_wit.Acl.open(name))

    @remap_wit_errors(MAPPINGS)
    def lookup(self, ip_addr: IpAddress) -> Pollable | None:
        """Performs a lookup of the given IP address in the ACL.

        If any matches are found, the result is a JSON-encoded HTTP body.

        If no matches are found, then `ok(none)` is returned. This corresponds
        to an HTTP error code of 204, “No Content”.
        """
        return Pollable(self._wit_resource.lookup(ip_addr))


