# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""Async IO support.

This module provides several utilities for performing I/O asynchronously.
See the documentation for `async-io.pollable` for a description of the kinds
of events it supports.

In the future, this interface is expected to be replaced by
[integrated async features].

[integrated async features]: https://github.com/WebAssembly/component-model/blob/main/design/mvp/Async.md#-async-explainer
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import async_io as _wit

from fastly_compute._resource import FastlyResource

__all__ = [
    "Pollable",
    "select",
    "select_with_timeout",
]


class Pollable(FastlyResource[_wit.Pollable]):
    """An object supporting generic async operations.

    Can be a `http-body.body`, `http-req.pending-response`, `http-req.pending-request`,
    `cache.pending-entry`. `kv-store.pending-lookup`, `kv-store.pending-insert`,
    `kv-store.pending-delete`, or `kv-store.pending-list`.

    Each async item has an associated I/O action:

    * Pending requests: awaiting the response headers / `response` object
    * Normal bodies: reading bytes from the body
    * Streaming bodies: writing bytes to the body

    For writing bytes, there is a large buffer associated with the handle that bytes
    can eagerly be written into, even before the origin itself consumes that data.
    """

    def is_ready(self) -> bool:
        """Make a nonblocking attempt to complete the I/O operation.

        Returns `True` if the given async item is “ready” for its associated I/O action, `False`
        otherwise.

        If an object is ready, the I/O action is guaranteed to complete without blocking.

        Valid object handles includes bodies and pending requests. See the `async-io.pollable`
        definition for more details, including what I/O actions are associated with each handle
        type.
        """
        return self._wit_resource.is_ready()

    @classmethod
    def new_ready(cls) -> Self:
        """Create a new trivial `pollable` which reports being immediately ready."""
        return cls(_wit.Pollable.new_ready())


def select(handles: list[Pollable]) -> int:
    """Blocks until one of the given objects is ready for I/O.

    If an object is ready, the I/O action is guaranteed to complete without blocking.

    Valid object handles includes bodies and pending requests. See the `async-io.pollable`
    definition for more details, including what I/O actions are associated with each handle
    type.

    Returns the *index* (not handle!) of the first object that is ready.

    Traps if the list is empty.
    """
    return _wit.select(handles)


def select_with_timeout(handles: list[Pollable], timeout_ms: int) -> int | None:
    """Blocks until one of the given objects is ready for I/O, or the timeout expires.

    If an object is ready, the I/O action is guaranteed to complete without blocking.

    Valid object handles includes bodies and pending requests. See the `async-io.pollable`
    definition for more details, including what I/O actions are associated with each handle
    type.

    The timeout is specified in milliseconds.

    Returns the *index* (not handle!) of the first object that is ready, or `None` if the
    timeout expires before any objects are ready for I/O.
    """
    return _wit.select_with_timeout(handles, timeout_ms)
