# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Backends] API.

A backend represents a service that the application can send requests to, potentially
caching the responses received.

Backends come in one of two flavors:
  * **Static Backends**: These backends are created using the Fastly UI or API,
    and are predefined by the user. Static backends typically have short names that are
    usable across every instance of a service.
  * **Dynamic Backends**: These backends are created programmatically using the
    `register-dynamic-backend` API. They are defined at runtime, and may or may not
    be shared across sandboxes depending on how they are configured.

To use a backend, pass it to a `send*` function.

Future versions of this function may return an error if your service does not have a backend
with this name.

[Backends]: https://www.fastly.com/documentation/guides/integrations/non-fastly-services/developer-guide-backends/
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import backend as _wit
from wit_world.imports.backend import BackendHealth

from fastly_compute._bindings.secret_store import Secret
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Backend",
    "BackendHealth",
    "DynamicBackendOptions",
    "register_dynamic_backend",
]


class DynamicBackendOptions(FastlyResource[_wit.DynamicBackendOptions]):
    """Options for `register-dynamic-backend`."""

    @classmethod
    def new(cls) -> Self:
        """Constructs an options resource with default values for all other possible fields for the
        backend, which can be overridden using the other methods provided.
        """
        return cls(_wit.DynamicBackendOptions())

    def override_host(self, value: str) -> None:
        """Sets a host header override when contacting this backend.

        This will force the value of the “Host” header to the given string when sending out the
        origin request. If this is not set and no header already exists, the “Host” header will
        default to the target.

        For more information, see [the Fastly documentation on override hosts].

        [the Fastly documentation on override hosts]: https://docs.fastly.com/en/guides/specifying-an-override-host>
        """
        return self._wit_resource.override_host(value)

    def connect_timeout(self, value: int) -> None:
        """Sets the connection timeout, in milliseconds, for this backend.

        Defaults to 1,000ms (1s).
        """
        return self._wit_resource.connect_timeout(value)

    def first_byte_timeout(self, value: int) -> None:
        """Sets a timeout, in milliseconds, that applies between the time of connection and the time we
        get the first byte back.

        Defaults to 15,000ms (15s).
        """
        return self._wit_resource.first_byte_timeout(value)

    def between_bytes_timeout(self, value: int) -> None:
        """Sets a timeout, in milliseconds, that applies between any two bytes we receive across the
        wire.

        Defaults to 10,000ms (10s).
        """
        return self._wit_resource.between_bytes_timeout(value)

    def use_tls(self, value: bool) -> None:
        """Enables or disables TLS to connect to the backend.

        When using TLS, Fastly checks the validity of the backend’s certificate, and fails the
        connection if the certificate is invalid. This check is not optional: an invalid
        certificate will cause the backend connection to fail (but read on).

        By default, the validity check does not require that the certificate hostname matches the
        hostname of your request. You can use `cert_hostname` to request a check of the
        certificate hostname.

        By default, certificate validity uses a set of public certificate authorities. You can
        specify an alternative CA using `ca_certificate`.
        """
        return self._wit_resource.use_tls(value)

    def tls_min_version(self, value: int) -> None:
        """Sets the minimum TLS version for connecting to the backend.

        Setting this will enable TLS for the connection as a side effect.
        """
        return self._wit_resource.tls_min_version(value)

    def tls_max_version(self, value: int) -> None:
        """Sets the maximum TLS version for connecting to the backend.

        Setting this will enable TLS for the connection as a side effect. (
        """
        return self._wit_resource.tls_max_version(value)

    def cert_hostname(self, value: str) -> None:
        """Defines the hostname that the server certificate should declare, and turn on validation
        during backend connections.

        You should enable this if you are using TLS, and setting this will enable TLS for the
        connection as a side effect.

        If `cert_hostname` is not provided (default), the server certificate’s hostname may
        have any value.
        """
        return self._wit_resource.cert_hostname(value)

    def ca_certificate(self, value: str) -> None:
        """Sets the CA certificate to use when checking the validity of the backend.

        Setting this will enable TLS for the connection as a side effect.

        If `ca_certificate` is not provided (default), the backends’s certificate is validated
        using a set of public root CAs.
        """
        return self._wit_resource.ca_certificate(value)

    def tls_ciphers(self, value: str) -> None:
        """Sets the acceptable cipher suites to use for TLS 1.0 - 1.2 connections.

        Setting this will enable TLS for the connection as a side effect.
        """
        return self._wit_resource.tls_ciphers(value)

    def sni_hostname(self, value: str) -> None:
        """Sets the SNI hostname for the backend connection.

        Setting this will enable TLS for the connection as a side effect.
        """
        return self._wit_resource.sni_hostname(value)

    def client_cert(self, client_cert: str, key: Secret) -> None:
        """Provides the given client certificate to the server as part of the TLS handshake.

        Setting this will enable TLS for the connection as a side effect. Both the certificate and
        the key to use should be in standard PEM format; providing the information in another
        format will lead to an error. We suggest that (at least the) key should be held in
        something like the Fastly secret store for security, with the handle passed to this
        function without unpacking it via `secret.plaintext`; the certificate can be held in a less
        secure medium.

        (If it is absolutely necessary to get the key from another source, we suggest the use of
        `secret.from-bytes`.
        """
        return self._wit_resource.client_cert(client_cert, key._wit_resource)

    def http_keepalive_time_ms(self, value: int) -> None:
        """Configures up to how long to allow HTTP keepalive connections to remain idle in the
        connection pool.
        """
        return self._wit_resource.http_keepalive_time_ms(value)

    def tcp_keepalive_enable(self, value: int) -> None:
        """Configures whether or not to use TCP keepalive on the connection to the backend."""
        return self._wit_resource.tcp_keepalive_enable(value)

    def tcp_keepalive_interval_secs(self, value: int) -> None:
        """Configures how long to wait in between each TCP keepalive probe sent to the backend."""
        return self._wit_resource.tcp_keepalive_interval_secs(value)

    def tcp_keepalive_probes(self, value: int) -> None:
        """Configures up to how many TCP keepalive probes to send to the backend before the connection
        is considered dead.
        """
        return self._wit_resource.tcp_keepalive_probes(value)

    def tcp_keepalive_time_secs(self, value: int) -> None:
        """Configures how long to wait after the last sent data over the TCP connection before starting
        to send TCP keepalive probes.
        """
        return self._wit_resource.tcp_keepalive_time_secs(value)

    def max_connections(self, value: int) -> None:
        """Configures the maximum number of connections to keep in the local connection pool.

        `0` is unlimited.

        Note that this limit is best determined experimentally, since the total number of
        connections to the backend will depend on POP sizes, HTTP keepalive limits, and the
        traffic patterns for individual POPs.
        """
        return self._wit_resource.max_connections(value)

    def max_use(self, value: int) -> None:
        """Configures how many times a pooled connection can be used.

        `0` is unlimited.
        """
        return self._wit_resource.max_use(value)

    def max_lifetime_ms(self, value: int) -> None:
        """Configures an upper bound for how long an HTTP keepalive connection can be open before we
        stop trying to reuse it.

        `0` is unlimited.
        """
        return self._wit_resource.max_lifetime_ms(value)

    def pooling(self, value: bool) -> None:
        """Determines whether or not connections to the same backend should be pooled across different
        sandboxes.

        Fastly considers two backends “the same” if they’re registered with the same name and
        the exact same settings. In those cases, when pooling is enabled, if one sandbox
        opens a connection to this backend it will be left open, and can be re-used by a different
        sandbox. This can help improve backend latency, by removing the need for the initial
        network / TLS handshake(s).

        By default, pooling is enabled for dynamic backends.
        """
        return self._wit_resource.pooling(value)

    def grpc(self, value: bool) -> None:
        """Sets whether or not this backend will be used for gRPC traffic.

        Warning: Setting this for backends that will not be used with gRPC may have unpredictable
        effects. Fastly only currently guarantees that this connection will work for gRPC traffic.
        """
        return self._wit_resource.grpc(value)

    def prefer_ipv6(self, value: bool) -> None:
        """Whether to prefer attempting connections to IPv6 addresses over IPv4 addresses when a
        hostname has both A and AAAA records.

        The Compute platform defaults to `True`, and will attempt IPv6 first if a AAAA record
        is present.
        """
        return self._wit_resource.prefer_ipv6(value)


class Backend(FastlyResource[_wit.Backend]):
    """Backend."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Attempts to open the named static backend.

        :raises ~fastly_compute.exceptions.types.open_error.OpenError:
        """
        return cls(_wit.Backend.open(name))

    def get_name(self) -> str:
        """Returns the name of this backend."""
        return self._wit_resource.get_name()

    @remap_wit_errors(MAPPINGS)
    def is_healthy(self) -> BackendHealth:
        """Returns the health of the backend if configured and currently known.

        For backends without a configured healthcheck, this will always return
        `backend-health.unknown`.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.is_healthy()

    @remap_wit_errors(MAPPINGS)
    def is_dynamic(self) -> bool:
        """Returns `True` if the backend is a “dynamic” backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.is_dynamic()

    @remap_wit_errors(MAPPINGS)
    def get_host(self, max_len: int) -> str:
        """Gets the host of this backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_host(max_len)

    @remap_wit_errors(MAPPINGS)
    def get_override_host(self, max_len: int) -> bytes | None:
        """Gets the “override host” for this backend.

        This is used to change the `Host` header sent to the backend. See
        [the Fastly documentation on override hosts].

        [the Fastly documentation on override hosts]: https://docs.fastly.com/en/guides/specifying-an-override-host

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_override_host(max_len)

    @remap_wit_errors(MAPPINGS)
    def get_port(self) -> int:
        """Gets the remote TCP port of the backend connection for the request.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_port()

    @remap_wit_errors(MAPPINGS)
    def get_connect_timeout_ms(self) -> int:
        """Gets the connection timeout of the backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_connect_timeout_ms()

    @remap_wit_errors(MAPPINGS)
    def get_first_byte_timeout_ms(self) -> int:
        """Gets the first byte timeout of the backend.

        This timeout applies between the time of connection and the time we get the first byte back.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_first_byte_timeout_ms()

    @remap_wit_errors(MAPPINGS)
    def get_between_bytes_timeout_ms(self) -> int:
        """Gets the between byte timeout of the backend.

        This timeout applies between any two bytes we receive across the wire.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_between_bytes_timeout_ms()

    @remap_wit_errors(MAPPINGS)
    def is_tls(self) -> bool:
        """Returns `True` if the backend is configured to use TLS.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.is_tls()

    @remap_wit_errors(MAPPINGS)
    def get_tls_min_version(self) -> int | None:
        """Gets the minimum TLS version this backend will use.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tls_min_version()

    @remap_wit_errors(MAPPINGS)
    def get_tls_max_version(self) -> int | None:
        """Gets the maximum TLS version this backend will use.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tls_max_version()

    @remap_wit_errors(MAPPINGS)
    def get_http_keepalive_time(self) -> int:
        """Returns the time for this backend to hold onto an idle HTTP keepalive connection
        after it was last used before closing it.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_http_keepalive_time()

    @remap_wit_errors(MAPPINGS)
    def get_tcp_keepalive_enable(self) -> bool:
        """Returns `True` if TCP keepalives have been enabled for this backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tcp_keepalive_enable()

    @remap_wit_errors(MAPPINGS)
    def get_tcp_keepalive_interval(self) -> int:
        """Returns the time to wait in between sending each TCP keepalive probe to this backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tcp_keepalive_interval()

    @remap_wit_errors(MAPPINGS)
    def get_tcp_keepalive_probes(self) -> int:
        """Returns the time to wait after the last data was sent before starting to send TCP keepalive
        probes to this backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tcp_keepalive_probes()

    @remap_wit_errors(MAPPINGS)
    def get_tcp_keepalive_time(self) -> int:
        """Returns the time to wait after the last data was sent before starting to send TCP keepalive
        probes to this backend.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_tcp_keepalive_time()


@remap_wit_errors(MAPPINGS)
def register_dynamic_backend(
    prefix: str, target: str, options: DynamicBackendOptions
) -> Backend:
    """Creates a new dynamic backend.

    The arguments are the name of the new backend to use, along with a string describing the
    backend host. The latter can be of the form:

    - "<ip address>"
    - "<hostname>"
    - "<ip address>:<port>"
    - "<hostname>:<port>"

    The name can be whatever you would like, as long as it does not match the name of any of the
    static service backends nor match any other dynamic backends built during this service
    instance. (Names can overlap between different instances of the same service—they will be
    treated as completely separate entities and will not be pooled—but you cannot, for example,
    declare a dynamic backend named “dynamic-backend” twice in the same sandbox.)

    Dynamic backends must be enabled for the Compute service. You can determine whether or not
    dynamic backends have been allowed for the current service by checking for the
    `error.unsupported` error result. This error only arises when attempting to use dynamic
    backends with a service that has not had dynamic backends enabled, or dynamic backends have
    been administratively prohibited for the node in response to an ongoing incident.

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return Backend(_wit.register_dynamic_backend(prefix, target, options._wit_resource))
