# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Core Cache] API

[Core Cache]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/#core-cache
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import cache as _wit
from wit_world.imports.cache import LookupState

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class LookupOptions:
    """Options for cache lookup operations; currently used for both `lookup` and
    `transaction-lookup`.
    """

    def __init__(
        self,
        request_headers: Request | None = None,
        always_use_requested_range: bool = False,
    ) -> None:
        self._wit = _wit.LookupOptions(
            request_headers=request_headers._wit_resource if request_headers is not None else None,
            always_use_requested_range=always_use_requested_range,
            extra=None,
        )

class WriteOptions:
    """Configuration for several functions that write to the cache:
    - `insert`
    - `transaction-insert`
    - `transaction-insert-and-stream-back`
    - `transaction-update`

    Some options are only allowed for certain of these hostcalls; see the comments
    on the fields.
    """

    def __init__(
        self,
        max_age_ns: int = 0,
        request_headers: Request | None = None,
        vary_rule: str | None = None,
        initial_age_ns: int | None = None,
        stale_while_revalidate_ns: int | None = None,
        surrogate_keys: str | None = None,
        length: int | None = None,
        user_metadata: bytes | None = None,
        edge_max_age_ns: int | None = None,
        sensitive_data: bool = False,
    ) -> None:
        self._wit = _wit.WriteOptions(
            max_age_ns=max_age_ns,
            request_headers=request_headers._wit_resource if request_headers is not None else None,
            vary_rule=vary_rule,
            initial_age_ns=initial_age_ns,
            stale_while_revalidate_ns=stale_while_revalidate_ns,
            surrogate_keys=surrogate_keys,
            length=length,
            user_metadata=user_metadata,
            edge_max_age_ns=edge_max_age_ns,
            sensitive_data=sensitive_data,
            extra=None,
        )

class GetBodyOptions:
    """GetBodyOptions."""

    def __init__(
        self,
        from_: int | None = None,
        to: int | None = None,
    ) -> None:
        self._wit = _wit.GetBodyOptions(
            from_=from_,
            to=to,
            extra=None,
        )

class ReplaceOptions:
    """Options for cache replace operations"""

    def __init__(
        self,
        request_headers: Request | None = None,
        replace_strategy: ReplaceStrategy | None = None,
        always_use_requested_range: bool = False,
    ) -> None:
        self._wit = _wit.ReplaceOptions(
            request_headers=request_headers._wit_resource if request_headers is not None else None,
            replace_strategy=replace_strategy,
            always_use_requested_range=always_use_requested_range,
            extra=None,
        )


class Entry(FastlyResource[_wit.Entry]):
    """The outcome of a cache lookup (either bare or as part of a cache transaction)"""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def lookup(cls, key: bytes, options: LookupOptions) -> Self:
        """Performs a non-request-collapsing cache lookup.

        Returns a result without waiting for any request collapsing that may be ongoing.
        """
        return cls(_wit.Entry.lookup(key, options._wit))

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def transaction_lookup(cls, key: bytes, options: LookupOptions) -> Self:
        """The entrypoint to the request-collapsing cache transaction API.

        This operation always participates in request collapsing and may return stale objects. To
        bypass request collapsing, use `entry.lookup` or `insert` instead.
        """
        return cls(_wit.Entry.transaction_lookup(key, options._wit))

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def transaction_lookup_async(cls, key: bytes, options: LookupOptions) -> Pollable:
        """The entrypoint to the request-collapsing cache transaction API, returning instead of waiting
        on busy.

        This operation always participates in request collapsing and may return stale objects. To
        bypass request collapsing, use `entry.lookup` or `insert` instead.
        """
        return Pollable(_wit.Entry.transaction_lookup_async(key, options._wit))

    @remap_wit_errors(MAPPINGS)
    def transaction_insert(self, options: WriteOptions) -> Pollable:
        """Inserts an object into the cache with the given metadata.

        Can only be used in if the cache handle state includes the `must-insert-or-update` flag.

        The returned handle is to a streaming body that is used for writing the object into
        the cache.
        """
        return Pollable(self._wit_resource.transaction_insert(options._wit))

    @remap_wit_errors(MAPPINGS)
    def transaction_insert_and_stream_back(self, options: WriteOptions) -> tuple[Pollable, Self]:
        """Inserts an object into the cache with the given metadata, and return a readable stream of the
        bytes as they are stored.

        This helps avoid the “slow reader” problem on a teed stream, for example when a program
        wishes to store a backend request in the cache while simultaneously streaming to a client
        in an HTTP response.

        The returned body handle is to a streaming body that is used for writing the object *into*
        the cache. The returned cache handle provides a separate transaction for reading out the
        newly cached object to send elsewhere.
        """
        _r = self._wit_resource.transaction_insert_and_stream_back(options._wit)
        return (Pollable(_r[0]), Entry(_r[1]))

    @remap_wit_errors(MAPPINGS)
    def transaction_update(self, options: WriteOptions) -> None:
        """Update the metadata of an object in the cache without changing its data.

        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must-insert-or-update`
        """
        return self._wit_resource.transaction_update(options._wit)

    @remap_wit_errors(MAPPINGS)
    def get_state(self) -> LookupState:
        """Get the state of a cache lookup, waiting for the lookup to complete if necessary.

        Note that FOUND == USABLE, and means "usable" (fresh or stale-while-revalidate).
        Some SDKs were released that checked only FOUND to infer "usable";
        we preserve the equivalence for backwards compatibility.
        """
        return self._wit_resource.get_state()

    @remap_wit_errors(MAPPINGS)
    def get_user_metadata(self, max_len: int) -> bytes | None:
        """Gets the user metadata of the found object, returning `ok(none)` if no object
        was found.
        """
        return self._wit_resource.get_user_metadata(max_len)

    @remap_wit_errors(MAPPINGS)
    def get_body(self, options: GetBodyOptions) -> Pollable:
        """Gets a range of the found object body, returning `ok(none)` if there
        was no found object.

        The returned `body` must be closed before calling this function again on the same
        `entry`.

        Note: until the CacheD protocol is adjusted to fully support this functionality,
        the body of objects that are past the stale-while-revalidate period will not
        be available, even when other metadata is.
        """
        return Pollable(self._wit_resource.get_body(options._wit))

    @remap_wit_errors(MAPPINGS)
    def get_length(self) -> int | None:
        """Gets the content length of the found object, returning `ok(none)` if
        there was no found object, or no content length was provided.
        """
        return self._wit_resource.get_length()

    @remap_wit_errors(MAPPINGS)
    def get_max_age_ns(self) -> int | None:
        """Gets the configured max age of the found object, returning `ok(none)`
        if there was no found object.
        """
        return self._wit_resource.get_max_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_stale_while_revalidate_ns(self) -> int | None:
        """Gets the configured stale-while-revalidate period of the found object, returning `ok(none)`
        if there was no found object.
        """
        return self._wit_resource.get_stale_while_revalidate_ns()

    @remap_wit_errors(MAPPINGS)
    def get_age_ns(self) -> int | None:
        """Gets the age of the found object, returning `ok(none)` if there
        was no found object.
        """
        return self._wit_resource.get_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_hits(self) -> int | None:
        """Gets the number of cache hits for the found object, returning `ok(none)`
        if there was no found object.
        """
        return self._wit_resource.get_hits()

    @remap_wit_errors(MAPPINGS)
    def transaction_cancel(self) -> None:
        """Cancel an obligation to provide an object to the cache.

        Useful if there is an error before streaming is possible, for example if a backend is
        unreachable.
        """
        return self._wit_resource.transaction_cancel()

class ReplaceEntry(FastlyResource[_wit.ReplaceEntry]):
    """A replace operation."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def replace(cls, key: bytes, options: ReplaceOptions) -> Self:
        """The entrypoint to the replace API.

        This operation always participates in request collapsing and may return stale objects.
        """
        return cls(_wit.ReplaceEntry.replace(key, options._wit))

    @remap_wit_errors(MAPPINGS)
    def get_age_ns(self) -> int | None:
        """Gets the age of the existing object during replace, returning
        `ok(none)` if there was no object.
        """
        return self._wit_resource.get_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_body(self, options: GetBodyOptions) -> Pollable | None:
        """Gets a range of the existing object body, returning `ok(none)` if there
        was no existing object.

        The returned `body` must be closed before calling this function
        again on the same `replace-entry`.
        """
        return Pollable(self._wit_resource.get_body(options._wit))

    @remap_wit_errors(MAPPINGS)
    def get_hits(self) -> int | None:
        """Gets the number of cache hits for the existing object during replace,
        returning `ok(none)` if there was no object.
        """
        return self._wit_resource.get_hits()

    @remap_wit_errors(MAPPINGS)
    def get_length(self) -> int | None:
        """Gets the content length of the existing object during replace,
        returning `ok(none)` if there was no object, or no content
        length was provided.
        """
        return self._wit_resource.get_length()

    @remap_wit_errors(MAPPINGS)
    def get_max_age_ns(self) -> int | None:
        """Gets the configured max age of the existing object during replace,
        returning `ok(none)` if there was no object.
        """
        return self._wit_resource.get_max_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_stale_while_revalidate_ns(self) -> int | None:
        """Gets the configured stale-while-revalidate period of the existing
        object during replace, returning `ok(none)` if there was no
        object.
        """
        return self._wit_resource.get_stale_while_revalidate_ns()

    @remap_wit_errors(MAPPINGS)
    def get_state(self) -> LookupState | None:
        """Gets the lookup state of the existing object during replace, returning
        `ok(none)` if there was no object.

        Note that FOUND == USABLE, and means "usable" (fresh or stale-while-revalidate).
        Some SDKs were released that checked only FOUND to infer "usable";
        we preserve the equivalence for backwards compatibility.
        """
        return self._wit_resource.get_state()

    @remap_wit_errors(MAPPINGS)
    def get_user_metadata(self, max_len: int) -> bytes | None:
        """Gets the user metadata of the existing object during replace, returning
        `ok(none)` if there was no object.
        """
        return self._wit_resource.get_user_metadata(max_len)

class ExtraLookupOptions(FastlyResource[_wit.ExtraLookupOptions]):
    """Extensibility for `lookup-options`"""

    @classmethod
    def new(cls) -> Self:
        """Construct a new instance with default values."""
        return cls(_wit.ExtraLookupOptions())

class ExtraWriteOptions(FastlyResource[_wit.ExtraWriteOptions]):
    """Extensibility for `write-options`"""

    @classmethod
    def new(cls) -> Self:
        """Construct a new instance with default values."""
        return cls(_wit.ExtraWriteOptions())

class ExtraGetBodyOptions(FastlyResource[_wit.ExtraGetBodyOptions]):
    """Extensibility for `get-body-options`"""

class ExtraReplaceOptions(FastlyResource[_wit.ExtraReplaceOptions]):
    """Extensibility for `replace-options`"""

    @classmethod
    def new(cls) -> Self:
        """Construct a new instance with default values."""
        return cls(_wit.ExtraReplaceOptions())


@remap_wit_errors(MAPPINGS)
def insert(key: bytes, options: WriteOptions) -> Pollable:
    """Performs a non-request-collapsing cache insertion (or update).

    The returned handle is to a streaming body that is used for writing the object into
    the cache.
    """
    return Pollable(_wit.insert(key, options._wit))

@remap_wit_errors(MAPPINGS)
def await_entry(handle: Pollable) -> Entry:
    """Continues the lookup transaction from which the given busy handle was returned,
    waiting for the leader transaction if request collapsed, and returns a cache handle.
    """
    return Entry(_wit.await_entry(handle._wit_resource))

@remap_wit_errors(MAPPINGS)
def close_pending_entry(handle: Pollable) -> None:
    """Closes an interaction with the cache that has not yet finished request collapsing."""
    return _wit.close_pending_entry(handle._wit_resource)

@remap_wit_errors(MAPPINGS)
def close_entry(handle: Entry) -> None:
    """Closes an ongoing interaction with the cache.

    If the cache handle state includes the `must-insert-or-update` (and hence no insert or
    update has been performed), closing the handle cancels any request collapsing, potentially
    choosing a new waiter to perform the insertion/update.
    """
    return _wit.close_entry(handle._wit_resource)

@remap_wit_errors(MAPPINGS)
def replace_insert(handle: ReplaceEntry, options: WriteOptions) -> Pollable:
    """Replace an object in the cache with the given metadata

    The returned handle is to a streaming body that is used for writing the object into
    the cache.
    """
    return Pollable(_wit.replace_insert(handle._wit_resource, options._wit))

@remap_wit_errors(MAPPINGS)
def close_replace_entry(handle: ReplaceEntry) -> None:
    """Closes an ongoing replace interaction with the cache.

    If the replace handle state includes the `must-insert-or-update` (and hence no insert or
    update has been performed), closing the handle cancels any request collapsing, potentially
    choosing a new waiter to perform the insertion/update.
    """
    return _wit.close_replace_entry(handle._wit_resource)

