# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Config Store] API.

[Config Store]: https://www.fastly.com/documentation/guides/concepts/edge-state/dynamic-config/#config-stores
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import config_store as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Store",
]




class Store(FastlyResource[_wit.Store]):
    """A Config Store."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Attempts to open the named config store.

        Names are case sensitive.
        """
        return cls(_wit.Store.open(name))

    @remap_wit_errors(MAPPINGS)
    def get(self, key: str, max_len: int) -> str | None:
        """Fetches a value from the config store, returning `ok(none)` if it doesn't exist."""
        return self._wit_resource.get(key, max_len)


