# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""Device detection based on the User-Agent header."""

from __future__ import annotations

from wit_world.imports import device_detection as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors

__all__ = [
    "lookup",
]





@remap_wit_errors(MAPPINGS)
def lookup(user_agent: str, max_len: int) -> str | None:
    """Looks up the data associated with a particular User-Agent string.

    Returns a list of bytes containing JSON-encoded device data. See [here] for descriptions
    of the JSON fields.

    [here]: https://www.fastly.com/documentation/reference/vcl/variables/client-request/client-identified/
    """
    return _wit.lookup(user_agent, max_len)

