# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Compute Dictionaries] (deprecated in favor of `config-store`)

[Compute Dictionaries]: https://www.fastly.com/documentation/guides/concepts/edge-state/dynamic-config/#dictionaries
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import dictionary as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class Dictionary(FastlyResource[_wit.Dictionary]):
    """A Compute Dictionary."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens a dictionary, given its name.

        Names are case sensitive.
        """
        return cls(_wit.Dictionary.open(name))

    @remap_wit_errors(MAPPINGS)
    def lookup(self, key: str, max_len: int) -> str | None:
        """Tries to look up a value in this dictionary.

        If the lookup is successful, this function returns `ok(some(s))` containing the found
        string `s`, or `ok(none)` if no entry with the given key was found.
        """
        return self._wit_resource.lookup(key, max_len)


