# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Edge rate limiting] API.

[Edge rate limiting]: https://docs.fastly.com/products/edge-rate-limiting
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import erl as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class RateCounter(FastlyResource[_wit.RateCounter]):
    """A rate counter that can be used with a edge rate limiter or
    standalone for counting and rate calculations.
    """

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens a `rate-counter` with the given name."""
        return cls(_wit.RateCounter.open(name))

    def get_name(self) -> str:
        """Returns the name of this rate counter."""
        return self._wit_resource.get_name()

    @remap_wit_errors(MAPPINGS)
    def check_rate(self, entry: str, delta: int, window: int, limit: int, penalty_box: PenaltyBox, ttl: int) -> bool:
        """Increments an entry in a rate counter and check if the client has exceeded some average number
        of requests per second (RPS) over the window.

        If the client is over the rps limit for the window, add to the penaltybox for ttl. Valid ttl
        span is 1m to 1h and TTL value is truncated to the nearest minute.

        Returns `true` if the client is penalized (i.e. should be limited), or `false` if not.
        """
        return self._wit_resource.check_rate(entry, delta, window, limit, penalty_box._wit_resource, ttl)

    @remap_wit_errors(MAPPINGS)
    def increment(self, entry: str, delta: int) -> None:
        """Increments an entry in the ratecounter by `delta`."""
        return self._wit_resource.increment(entry, delta)

    @remap_wit_errors(MAPPINGS)
    def lookup_rate(self, entry: str, window: int) -> int:
        """Looks up the current rate for entry in the ratecounter for a window."""
        return self._wit_resource.lookup_rate(entry, window)

    @remap_wit_errors(MAPPINGS)
    def lookup_count(self, entry: str, duration: int) -> int:
        """Looks up the current count for entry in the ratecounter for duration."""
        return self._wit_resource.lookup_count(entry, duration)

class PenaltyBox(FastlyResource[_wit.PenaltyBox]):
    """A penaltybox that can be used with the edge rate limiter or
    standalone for adding and checking if some entry is in the data set.
    """

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens a `penalty-box` identified by the given name."""
        return cls(_wit.PenaltyBox.open(name))

    def get_name(self) -> str:
        """Returns the name of this penaltybox."""
        return self._wit_resource.get_name()

    @remap_wit_errors(MAPPINGS)
    def add(self, entry: str, ttl: int) -> None:
        """Adds `entry` to a the penaltybox for the duration of ttl.

        Valid ttl span is 1m to 1h and TTL value is truncated to the nearest minute.
        """
        return self._wit_resource.add(entry, ttl)

    @remap_wit_errors(MAPPINGS)
    def has(self, entry: str) -> bool:
        """Checks if `entry` is in the penaltybox."""
        return self._wit_resource.has(entry)


