# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Geographic data] for IP addresses.

[Geographic data]: https://www.fastly.com/blog/improve-performance-and-gain-better-end-user-intelligence-geoip-geography-detection
"""

from __future__ import annotations

from wit_world.imports import geo as _wit
from wit_world.imports.types import IpAddress

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors

__all__ = [
    "IpAddress",
    "lookup",
]


@remap_wit_errors(MAPPINGS)
def lookup(ip_addr: IpAddress, max_len: int) -> str:
    """Looks up the geographic data associated with a particular IP address.

    Returns a list of bytes containing JSON-encoded geographic data. See [here] for descriptions
    of the JSON fields.

    [here]: https://www.fastly.com/documentation/reference/vcl/variables/geolocation/

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.lookup(ip_addr, max_len)
