# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""The exported interface.

The `handle` function serves as the main entrypoint to applications. Unlike the
rest of the interfaces in this package, this `http-incoming` interface is exported by
applications rather than imported, which means that this is a function defined
by the application and called from the outside, rather than a function called
by the application into the outside.
"""

from __future__ import annotations

from wit_world.imports import http_incoming as _wit

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._bindings.http_req import Request
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors


@remap_wit_errors(MAPPINGS)
def handle(request: Request, body: Pollable) -> None:
    """Handle the given request.

    This function is called once per sandbox. When it returns, the
    sandbox exits. To opt into receiving multiple requests in a single
    sandbox, use `http-downstream.next-request`.

    To send a response for the given `request`, use `send-downstream`, or to
    stream the response body after the response has been initiated, use
    `send-downstream-streaming`.
    """
    return _wit.handle(request._wit_resource, body._wit_resource)

