# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""HTTP downstream requests and metadata.

“Downstream” here refers to incoming HTTP requests.
"""

from __future__ import annotations

from wit_world.imports import http_downstream as _wit
from wit_world.imports.http_req import ClientCertVerifyResult
from wit_world.imports.types import IpAddress

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._bindings.http_req import Request
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class NextRequestOptions:
    """Configuration for `next-request`."""

    def __init__(
        self,
        timeout_ms: int | None = None,
    ) -> None:
        self._wit = _wit.NextRequestOptions(
            timeout_ms=timeout_ms,
            extra=None,
        )


class ExtraNextRequestOptions(FastlyResource[_wit.ExtraNextRequestOptions]):
    """Extensibility for `next-request-options`"""


@remap_wit_errors(MAPPINGS)
def next_request(options: NextRequestOptions) -> Pollable:
    """Prepares to accept a new downstream request.

    By default, each sandbox accepts a single downstream request,
    passed in as an argument to the `http-incoming.handle` call. The
    `next-request` function enables a sandbox to accept additional
    downstream requests. `next-request` returns a `pending-request`, which
    can be passed to `await-request` to wait for the request to become
    available and return the `request`.

    When using this function, be mindful of two considerations:

     - When a single sandbox accepts multiple requests, its state
       isn't automatically cleared between requests. Applications are
       therefore responsible for preventing sensitive data from leaking from
       one request to another.

     - There is no guarantee that a single sandbox will receive all
       requests from a given client or from a given location. When it is
       necessary to preserve state between multiple requests, store it outside
       of the sandbox.
    """
    return Pollable(_wit.next_request(options._wit))

@remap_wit_errors(MAPPINGS)
def await_request(pending: Pollable) -> tuple[Request, Pollable] | None:
    """Waits until the next request is available, and then returns the resulting
    request and body.

    Returns `ok(none)` if there are no more requests for this sandbox.
    """
    _r = _wit.await_request(pending._wit_resource)
    return (Request(_r[0]), Pollable(_r[1])) if _r is not None else None

@remap_wit_errors(MAPPINGS)
def downstream_original_header_names(ds_request: Request, max_len: int, cursor: int) -> tuple[str, int | None]:
    """Returns the client request's header names exactly as they were originally received.

    This includes both the original header name characters' cases, as well as the original order
    of the received headers.

    The first `cursor` names are skipped. The remaining names are encoded successively with
    a NUL byte after each into a list of bytes at most `max-len` long. If any of the remaining
    names don't fit, the returned `option<u32>` is the index of the first name that didn't fit,
    or `none` if all the remaining names fit. If `max-len` is too small to fit any name,
    an `error.buffer-len` error is returned, providing a recommended buffer size.
    """
    return _wit.downstream_original_header_names(ds_request._wit_resource, max_len, cursor)

@remap_wit_errors(MAPPINGS)
def downstream_original_header_count(ds_request: Request) -> int:
    """Returns the number of headers in the client request as originally received."""
    return _wit.downstream_original_header_count(ds_request._wit_resource)

def downstream_client_ip_addr(ds_request: Request) -> IpAddress | None:
    """Returns the IP address of the client making the HTTP request, if known."""
    return _wit.downstream_client_ip_addr(ds_request._wit_resource)

def downstream_server_ip_addr(ds_request: Request) -> IpAddress | None:
    """Returns the IP address on which this server received the HTTP request, if known."""
    return _wit.downstream_server_ip_addr(ds_request._wit_resource)

@remap_wit_errors(MAPPINGS)
def downstream_client_h2_fingerprint(ds_request: Request, max_len: int) -> str:
    """Gets the HTTP/2 fingerprint of client request if available."""
    return _wit.downstream_client_h2_fingerprint(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_client_request_id(ds_request: Request, max_len: int) -> str:
    """Gets the id of the current request if available."""
    return _wit.downstream_client_request_id(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_client_oh_fingerprint(ds_request: Request, max_len: int) -> str:
    """Gets the fingerprint of client request headers if available."""
    return _wit.downstream_client_oh_fingerprint(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_client_ddos_detected(ds_request: Request) -> bool:
    """Returns whether the request was tagged as contributing to a DDoS attack."""
    return _wit.downstream_client_ddos_detected(ds_request._wit_resource)

@remap_wit_errors(MAPPINGS)
def downstream_tls_cipher_openssl_name(ds_request: Request, max_len: int) -> list[int] | None:
    """Gets the cipher suite used to secure the downstream client TLS connection.

    The value returned will be consistent with the [OpenSSL name] for the cipher suite.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.

    [OpenSSL name]: https://testssl.sh/openssl-iana.mapping.html
    """
    return _wit.downstream_tls_cipher_openssl_name(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_tls_protocol(ds_request: Request, max_len: int) -> list[int] | None:
    """Gets the TLS protocol version used to secure the downstream client TLS connection.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    """
    return _wit.downstream_tls_protocol(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_tls_client_hello(ds_request: Request, max_len: int) -> list[int] | None:
    """Gets the raw bytes sent by the client in the TLS ClientHello message.

    See [RFC 5246] for details.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.

    [RFC 5246]: https://www.rfc-editor.org/rfc/rfc5246#section-7.4.1.2
    """
    return _wit.downstream_tls_client_hello(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_tls_raw_client_certificate(ds_request: Request, max_len: int) -> list[int] | None:
    """Gets the raw client certificate used to secure the downstream client mTLS connection.

    The value returned will be based on PEM format.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    """
    return _wit.downstream_tls_raw_client_certificate(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_tls_client_cert_verify_result(ds_request: Request) -> ClientCertVerifyResult | None:
    """Returns the `client-cert-verify-result` from the downstream client mTLS handshake.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    """
    return _wit.downstream_tls_client_cert_verify_result(ds_request._wit_resource)

@remap_wit_errors(MAPPINGS)
def downstream_tls_client_servername(ds_request: Request, max_len: int) -> str | None:
    """Returns the Server Name Indication from the downstream client TLS handshake.

    Returns `ok(none)` if not available.
    """
    return _wit.downstream_tls_client_servername(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_tls_ja3_md5(ds_request: Request) -> list[int] | None:
    """Gets the JA3 hash of the TLS ClientHello message.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    """
    return _wit.downstream_tls_ja3_md5(ds_request._wit_resource)

@remap_wit_errors(MAPPINGS)
def downstream_tls_ja4(ds_request: Request, max_len: int) -> str | None:
    """Gets the JA4 hash of the TLS ClientHello message.

    Returns `ok(none)` if the downstream client connection is not a TLS connection.
    """
    return _wit.downstream_tls_ja4(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def downstream_compliance_region(ds_request: Request, max_len: int) -> str | None:
    """Gets the compliance region that the client IP address is in."""
    return _wit.downstream_compliance_region(ds_request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def fastly_key_is_valid(ds_request: Request) -> bool:
    """Returns whether or not the original client request arrived with a
    Fastly-Key belonging to a user with the rights to purge content on this
    service.
    """
    return _wit.fastly_key_is_valid(ds_request._wit_resource)

