# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[HTTP Cache] API.

Overall, this should look very familiar to users of the Core Cache API. The primary differences
are:

- HTTP `request`s and `response`s are used rather than relying on the user to
  encode headers, status codes, etc in `user-metadata`.

- Convenience functions specific to HTTP semantics are provided, such as `is-request-cacheable`,
  `get-suggested-backend-request`, `get-suggested-write-options`, and
  `transaction-record-not-cacheable`.

The HTTP-specific behavior of these functions is intended to support applications that match the
normative guidance in [RFC 9111]. For example, `is-request-cacheable` returns `false` for `POST`
requests. However, this answer along with those of many of these functions explicitly provide
*suggestions*; they do not necessarily need to be followed if custom behavior is required, such
as caching `POST` responses when the application author knows that to be safe.

The starting points for this API are `lookup` (no request collapsing) and `transaction-lookup`
(request collapsing).

[HTTP Cache]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/cache-freshness/
[RFC 9111]: https://www.rfc-editor.org/rfc/rfc9111.html
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import http_cache as _wit
from wit_world.imports.cache import LookupState
from wit_world.imports.http_cache import StorageAction

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._bindings.backend import Backend
from fastly_compute._bindings.http_req import Request
from fastly_compute._bindings.http_resp import Response
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Entry",
    "LookupOptions",
    "LookupState",
    "StorageAction",
    "SuggestedWriteOptions",
    "WriteOptions",
    "close_entry",
    "get_suggested_cache_key",
    "is_request_cacheable",
]



class LookupOptions:
    """Non-required options for cache lookups."""

    def __init__(
        self,
        override_key: bytes | None = None,
        backend: Backend | None = None,
    ) -> None:
        self._wit = _wit.LookupOptions(
            override_key=override_key,
            backend=backend._wit_resource if backend is not None else None,
            extra=None,
        )

class WriteOptions:
    """Options for cache insertions and updates."""

    def __init__(
        self,
        max_age_ns: int = 0,
        vary_rule: str | None = None,
        initial_age_ns: int | None = None,
        stale_while_revalidate_ns: int | None = None,
        stale_if_error_ns: int | None = None,
        surrogate_keys: str | None = None,
        length: int | None = None,
        sensitive_data: bool = False,
    ) -> None:
        self._wit = _wit.WriteOptions(
            max_age_ns=max_age_ns,
            vary_rule=vary_rule,
            initial_age_ns=initial_age_ns,
            stale_while_revalidate_ns=stale_while_revalidate_ns,
            stale_if_error_ns=stale_if_error_ns,
            surrogate_keys=surrogate_keys,
            length=length,
            sensitive_data=sensitive_data,
            extra=None,
        )


class Entry(FastlyResource[_wit.Entry]):
    """An HTTP Cache transaction."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def transaction_lookup(cls, req_handle: Request, options: LookupOptions) -> Self:
        """Performs a cache lookup based on the given request.

        This operation always participates in request collapsing and may return an obligation to
        insert or update responses, and/or stale responses.

        The request is not consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return cls(_wit.Entry.transaction_lookup(req_handle._wit_resource, options._wit))

    @remap_wit_errors(MAPPINGS)
    def transaction_insert(self, resp_handle: Response, options: WriteOptions) -> Pollable:
        """Inserts a response into the cache with the given options, returning a streaming body handle
        that is ready for writing or appending.

        Can only be used if the cache handle state includes the `must_insert_or_update` flag.

        The response is consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return Pollable(self._wit_resource.transaction_insert(resp_handle._wit_resource, options._wit))

    @remap_wit_errors(MAPPINGS)
    def transaction_insert_and_stream_back(self, resp_handle: Response, options: WriteOptions) -> tuple[Pollable, Self]:
        """Inserts a response into the cache with the given options, and return a fresh cache handle
        that can be used to retrieve and stream the response while it's being inserted.

        This helps avoid the “slow reader” problem on a teed stream, for example when a program
        wishes to store a backend request in the cache while simultaneously streaming to a client
        in an HTTP response.

        The response is consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        _r = self._wit_resource.transaction_insert_and_stream_back(resp_handle._wit_resource, options._wit)
        return (Pollable(_r[0]), Entry(_r[1]))

    @remap_wit_errors(MAPPINGS)
    def transaction_update(self, resp_handle: Response, options: WriteOptions) -> None:
        """Updates freshness lifetime, response headers, and caching settings without updating the
        response body.

        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must_insert_or_update`

        The response is consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.transaction_update(resp_handle._wit_resource, options._wit)

    @remap_wit_errors(MAPPINGS)
    def transaction_update_and_return_fresh(self, resp_handle: Response, options: WriteOptions) -> Self:
        """Updates freshness lifetime, response headers, and caching settings without updating the
        response body, and return a fresh cache handle that can be used to retrieve and stream the
        stored response.

        Can only be used in if the cache handle state includes both of the flags:
        - `found`
        - `must_insert_or_update`

        The response is consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return Entry(self._wit_resource.transaction_update_and_return_fresh(resp_handle._wit_resource, options._wit))

    @remap_wit_errors(MAPPINGS)
    def transaction_record_not_cacheable(self, options: WriteOptions) -> None:
        """Disables request collapsing and response caching for this cache entry.

        In Varnish terms, this function stores a hit-for-pass object.

        Only the max age and, optionally, the vary rule are read from the `options`
        for this function.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.transaction_record_not_cacheable(options._wit)

    @remap_wit_errors(MAPPINGS)
    def get_suggested_backend_request(self) -> Request:
        """Prepares a suggested request to make to a backend to satisfy the looked-up request.

        If there is a stored, stale response, this suggested request may be for revalidation. If the
        looked-up request is ranged, the suggested request will be unranged in order to try caching
        the entire response.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return Request(self._wit_resource.get_suggested_backend_request())

    @remap_wit_errors(MAPPINGS)
    def get_suggested_write_options(self, response: Response) -> SuggestedWriteOptions:
        """Prepares a suggested set of cache write options for a given request and response pair.

        The response is not consumed.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return SuggestedWriteOptions(self._wit_resource.get_suggested_write_options(response._wit_resource))

    @remap_wit_errors(MAPPINGS)
    def prepare_response_for_storage(self, response: Response) -> tuple[StorageAction, Response]:
        """Adjusts a response into the appropriate form for storage and provides a storage action
        recommendation.

        For example, if the looked-up request contains conditional headers, this function will
        interpret a `304 Not Modified` response for revalidation by updating headers.

        In addition to the updated response, this function returns the recommended storage action.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        _r = self._wit_resource.prepare_response_for_storage(response._wit_resource)
        return (_r[0], Response(_r[1]))

    @remap_wit_errors(MAPPINGS)
    def get_found_response(self, transform_for_client: int) -> tuple[Response, Pollable] | None:
        """Retrieves a stored response from the cache, returning `None` if
        there was no response found.

        If `transform_for_client` is set, the response will be adjusted according to the looked-up
        request. For example, a response retrieved for a range request may be transformed into a
        `206 Partial Content` response with an appropriate `content_range` header.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        _r = self._wit_resource.get_found_response(transform_for_client)
        return (Response(_r[0]), Pollable(_r[1])) if _r is not None else None

    @remap_wit_errors(MAPPINGS)
    def get_state(self) -> LookupState:
        """Gets the state of a cache transaction.

        Primarily useful after performing the lookup to determine what subsequent operations are
        possible and whether any insertion or update obligations exist.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_state()

    @remap_wit_errors(MAPPINGS)
    def get_length(self) -> int | None:
        """Gets the length of the found response, returning `None` if there
        was no response found or no length was provided.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_length()

    @remap_wit_errors(MAPPINGS)
    def get_max_age_ns(self) -> int | None:
        """Gets the configured max age of the found response in nanoseconds, returning `None`
        if there was no response found.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_max_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_stale_while_revalidate_ns(self) -> int | None:
        """Gets the configured stale-while-revalidate period of the found response in nanoseconds,
        returning `None` if there was no response found.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_stale_while_revalidate_ns()

    @remap_wit_errors(MAPPINGS)
    def get_age_ns(self) -> int | None:
        """Gets the age of the found response in nanoseconds, returning `None`
        if there was no response found.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_hits(self) -> int | None:
        """Gets the number of cache hits for the found response, returning `None`
        if there was no response found.

        This figure only reflects hits for a stored response in a particular cache server
        or cluster, not the entire Fastly network.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_hits()

    @remap_wit_errors(MAPPINGS)
    def get_sensitive_data(self) -> bool | None:
        """Gets whether a found response is marked as containing sensitive data, returning `None`
        if there was no response found.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_sensitive_data()

    @remap_wit_errors(MAPPINGS)
    def get_surrogate_keys(self, max_len: int) -> str | None:
        """Gets the surrogate keys of the found response, returning `None` if
        there was no response found.

        The output is a list of surrogate keys separated by spaces.

        If the full list requires more than `max_len` bytes, an `error.buffer-len`
        error is returned containing the required size.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_surrogate_keys(max_len)

    @remap_wit_errors(MAPPINGS)
    def get_vary_rule(self, max_len: int) -> str | None:
        """Gets the vary rule of the found response, returning `None` if there
        was no response found.

        The output is a list of header names separated by spaces.

        If the full list requires more than `max_len` bytes, an `error.buffer-len`
        error is returned containing the required size.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_vary_rule(max_len)

    @remap_wit_errors(MAPPINGS)
    def transaction_abandon(self) -> None:
        """Abandons an obligation to provide a response to the cache.

        Useful if there is an error before streaming is possible, for example if a backend is
        unreachable.

        If there are other requests collapsed on this transaction, one of those other requests will
        be awoken and given the obligation to provide a response. If subsequent requests
        are unlikely to yield cacheable responses, this may lead to undesired serialization of
        requests. Consider using `transaction_record_not_cacheable` to make lookups for this request
        bypass the cache.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.transaction_abandon()

class ExtraLookupOptions(FastlyResource[_wit.ExtraLookupOptions]):
    """Extensibility for `lookup-options`"""

class ExtraWriteOptions(FastlyResource[_wit.ExtraWriteOptions]):
    """Extensibility for `write-options`"""

class SuggestedWriteOptions(FastlyResource[_wit.SuggestedWriteOptions]):
    """The methods in this resource return values that correspond to the fields in a
    `write-options`. This type is used when a `write-options` value would
    be returned, so that it can use `max-len` parameters when returning
    dynamically-sized data, and so that it excludes the `extra` field, since borrowed
    handles cannot be returned from functions.
    """

    def get_max_age_ns(self) -> int:
        """Returns the suggested value for the `write-options.max-age-ns` field."""
        return self._wit_resource.get_max_age_ns()

    @remap_wit_errors(MAPPINGS)
    def get_vary_rule(self, max_len: int) -> str:
        """Returns the suggested value for the `write-options.vary-rule` field.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_vary_rule(max_len)

    def get_initial_age_ns(self) -> int:
        """Returns the suggested value for the `write-options.initial-age-ns` field."""
        return self._wit_resource.get_initial_age_ns()

    def get_stale_while_revalidate_ns(self) -> int:
        """Returns the suggested value for the `write-options.stale-while-revalidate-ns` field."""
        return self._wit_resource.get_stale_while_revalidate_ns()

    @remap_wit_errors(MAPPINGS)
    def get_surrogate_keys(self, max_len: int) -> str:
        """Returns the suggested value for the `write-options.surrogate-keys` field.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.get_surrogate_keys(max_len)

    def get_length(self) -> int | None:
        """Returns the suggested value for the `write-options.length` field."""
        return self._wit_resource.get_length()

    def get_sensitive_data(self) -> bool:
        """Returns the suggested value for the `write-options.sensitive-data` field."""
        return self._wit_resource.get_sensitive_data()


@remap_wit_errors(MAPPINGS)
def is_request_cacheable(request: Request) -> bool:
    """Determines whether a request is cacheable per conservative [RFC 9111] semantics.

    In particular, this function checks whether the request method is `GET` or `HEAD`, and
    considers requests with other methods uncacheable. Applications where it is safe to cache
    responses to other methods should consider using their own cacheability check instead of
    this function.

    [RFC 9111]: https://www.rfc-editor.org/rfc/rfc9111.html

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.is_request_cacheable(request._wit_resource)

@remap_wit_errors(MAPPINGS)
def get_suggested_cache_key(request: Request, max_len: int) -> bytes:
    """Retrieves the default cache key for the request.

    If the full key requires more than `max_len` bytes, an `error.buffer-len`
    error is returned containing the required size.

    At the moment, HTTP cache keys must always be 32 bytes.

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.get_suggested_cache_key(request._wit_resource, max_len)

@remap_wit_errors(MAPPINGS)
def close_entry(handle: Entry) -> None:
    """Closes an ongoing interaction with the cache.

    If the cache handle state includes `must_insert_or_update` (and hence no insert or update
    has been performed), closing the handle cancels any request collapsing, potentially choosing
    a new waiter to perform the insertion/update.

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.close_entry(handle._wit_resource)

