# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Image Optimizer] API.

[Image Optimizer]: https://www.fastly.com/documentation/guides/full-site-delivery/image-optimization/about-fastly-image-optimizer/
"""

from __future__ import annotations

from wit_world.imports import image_optimizer as _wit

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._bindings.backend import Backend
from fastly_compute._bindings.http_req import Request
from fastly_compute._bindings.http_resp import Response
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class ImageOptimizerTransformOptions:
    """ImageOptimizerTransformOptions."""

    def __init__(
        self,
        sdk_claims_opts: str | None = None,
    ) -> None:
        self._wit = _wit.ImageOptimizerTransformOptions(
            sdk_claims_opts=sdk_claims_opts,
            extra=None,
        )


class ExtraImageOptimizerTransformOptions(FastlyResource[_wit.ExtraImageOptimizerTransformOptions]):
    """Extensibility for `image-optimizer-transform-options`"""


@remap_wit_errors(MAPPINGS)
def transform_image_optimizer_request(origin_image_request: Request, origin_image_request_body: Pollable | None, origin_image_request_backend: Backend, io_transform_options: ImageOptimizerTransformOptions) -> tuple[Response, Pollable]:
    """transform_image_optimizer_request."""
    _r = _wit.transform_image_optimizer_request(origin_image_request._wit_resource, origin_image_request_body, origin_image_request_backend._wit_resource, io_transform_options._wit)
    return (Response(_r[0]), Pollable(_r[1]))

