# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""Interface to Fastly's [Compute KV Store].

For a high-level introduction to this feature, see this [blog post].

[Compute KV Store]: https://www.fastly.com/documentation/guides/concepts/edge-state/data-stores/#kv-stores
[blog post]: https://www.fastly.com/blog/introducing-the-compute-edge-kv-store-global-persistent-storage-for-compute-functions
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import kv_store as _wit
from wit_world.imports.kv_store import InsertMode, ListMode

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource


class InsertOptions:
    """Options for configuring the behavior of the `insert` function."""

    def __init__(
        self,
        background_fetch: bool = False,
        if_generation_match: int | None = None,
        metadata: str | None = None,
        time_to_live_sec: int | None = None,
        mode: InsertMode = InsertMode.OVERWRITE,
    ) -> None:
        self._wit = _wit.InsertOptions(
            background_fetch=background_fetch,
            if_generation_match=if_generation_match,
            metadata=metadata,
            time_to_live_sec=time_to_live_sec,
            mode=mode,
            extra=None,
        )

class ListOptions:
    """Options for `list` and `list-async`."""

    def __init__(
        self,
        mode: ListMode = ListMode.STRONG,
        cursor: str | None = None,
        limit: int | None = None,
        prefix: str | None = None,
    ) -> None:
        self._wit = _wit.ListOptions(
            mode=mode,
            cursor=cursor,
            limit=limit,
            prefix=prefix,
            extra=None,
        )


class Store(FastlyResource[_wit.Store]):
    """A KV Store."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens the KV Store with the given name."""
        return cls(_wit.Store.open(name))

    @remap_wit_errors(MAPPINGS)
    def lookup(self, key: str) -> Entry | None:
        """Looks up a value in the KV Store.

        Returns `ok(some(v))` with the value `v` that was found, `ok(none)` if no value was
        found, or `err(e)` indicating the error `e` occurred.

        This function waits until the operation completes.
        """
        return Entry(self._wit_resource.lookup(key))

    @remap_wit_errors(MAPPINGS)
    def lookup_async(self, key: str) -> Pollable:
        """Look up a value in the KV Store asynchronously.

        This function initiates an async lookup of a value in the KV Store. Use
        `await-lookup` to finish the lookup.
        """
        return Pollable(self._wit_resource.lookup_async(key))

    @remap_wit_errors(MAPPINGS)
    def insert(self, key: str, body: Pollable, options: InsertOptions) -> None:
        """Inserts a value into the KV Store.

        If the KV Store already contains a value for this key, the `mode` field
        of the `options` argument specifies how the existing value is handled.

        This function waits until the operation completes.
        """
        return self._wit_resource.insert(key, body._wit_resource, options._wit)

    @remap_wit_errors(MAPPINGS)
    def insert_async(self, key: str, body: Pollable, options: InsertOptions) -> Pollable:
        """Insert a value into the KV Store asynchronously.

        If the KV Store already contains a value for this key, the `mode` field
        of the `options` argument specifies how the existing value is handled.

        This function initiates an async insert of a value in the KV Store. Use
        `await-insert` to finish the lookup.
        """
        return Pollable(self._wit_resource.insert_async(key, body._wit_resource, options._wit))

    @remap_wit_errors(MAPPINGS)
    def delete(self, key: str) -> bool:
        """Deletes a value in the KV Store.

        Returns `ok(true)` if a value was successfully deleted, `ok(false)` if no value was
        found, or `err(e)` indicating the error `e` occurred.

        This function waits until the operation completes.
        """
        return self._wit_resource.delete(key)

    @remap_wit_errors(MAPPINGS)
    def delete_async(self, key: str) -> Pollable:
        """Delete of a value in the KV Store.

        This function initiates an async delete of a value in the KV Store. Use
        `await-delete` to finish the lookup.
        """
        return Pollable(self._wit_resource.delete_async(key))

    @remap_wit_errors(MAPPINGS)
    def list(self, options: ListOptions) -> Pollable:
        """Lists keys in the KV Store.

        Returns `ok(b)` with the body `b` on success, or `err(e)` indicating the error `e`
        occurred.

        This function waits until the operation completes.
        """
        return Pollable(self._wit_resource.list(options._wit))

    @remap_wit_errors(MAPPINGS)
    def list_async(self, options: ListOptions) -> Pollable:
        """List of keys in the KV Store.

        This function initiates an async list value in the KV Store. Use
        `await-list` to finish the lookup.
        """
        return Pollable(self._wit_resource.list_async(options._wit))

class ExtraKvError(FastlyResource[_wit.ExtraKvError]):
    """Extensibility for `kv-error`"""

class Entry(FastlyResource[_wit.Entry]):
    """A response from a KV Store Lookup operation.

    This type holds the `body`, metadata, and generation of found key.
    """

    def take_body(self) -> Pollable | None:
        """Take and return the body from this `entry`, if it has one; otherwise return `none`.

        After calling this method, this entry will no longer have a body.
        """
        return Pollable(self._wit_resource.take_body())

    @remap_wit_errors(MAPPINGS)
    def metadata(self, max_len: int) -> str | None:
        """Read the metadata of the KV Store item, if present."""
        return self._wit_resource.metadata(max_len)

    def generation(self) -> int:
        """Read the current generation of the KV Store item."""
        return self._wit_resource.generation()

class ExtraInsertOptions(FastlyResource[_wit.ExtraInsertOptions]):
    """Extensibility for `insert-options`"""

class ExtraListOptions(FastlyResource[_wit.ExtraListOptions]):
    """Extensibility for `list-options`"""


@remap_wit_errors(MAPPINGS)
def await_lookup(handle: Pollable) -> Entry | None:
    """Wait on the async lookup of a value in the KV Store.

    Returns `ok(some(v))` with the value `v` that was found, `ok(none)` if no value was
    found, or `err(e)` indicating the error `e` occurred.
    """
    return Entry(_wit.await_lookup(handle._wit_resource))

@remap_wit_errors(MAPPINGS)
def await_insert(handle: Pollable) -> None:
    """Wait on the async insert of a value in the KV Store.

    Returns `ok` if the `insert` succeeded, or an error code on failure.
    """
    return _wit.await_insert(handle._wit_resource)

@remap_wit_errors(MAPPINGS)
def await_delete(handle: Pollable) -> bool:
    """Wait on the async delete of a value in the KV Store.

    Returns `ok(true)` if a value was successfully deleted, `ok(false)` if no value was
    found, or `err(e)` indicating the error `e` occurred.
    """
    return _wit.await_delete(handle._wit_resource)

@remap_wit_errors(MAPPINGS)
def await_list(handle: Pollable) -> Pollable:
    """Wait on the async list of keys in the KV Store.

    Returns `ok(b)` with the JSON-encoded body `b` on success, or `err(e)` indicating
    the error `e` occurred.
    """
    return Pollable(_wit.await_list(handle._wit_resource))

