# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""Low-level interface to Fastly's [Real-Time Log Streaming] endpoints.

[Real-Time Log Streaming]: https://docs.fastly.com/en/guides/about-fastlys-realtime-log-streaming-features
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import log as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Endpoint",
]


class Endpoint(FastlyResource[_wit.Endpoint]):
    """A logging endpoint."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        r"""Tries to get an endpoint by name.

        Currently, the conditions on an endpoint name are:
        - It must not be empty.
        - It must not contain newlines (`\n`) or colons (`:`).
        - It must not be `stdout` or `stderr`, which are reserved for debugging.

        Names are case sensitive. Calling `get_endpoint` with a name that doesn't correspond to any
        logging endpoint available in your service will still return a usable endpoint, and writes
        to that endpoint will succeed. Refer to your service dashboard to diagnose missing log
        events.

        :raises ~fastly_compute.exceptions.types.open_error.OpenError:
        """
        return cls(_wit.Endpoint.open(name))

    def write(self, msg: bytes) -> None:
        """Writes a data to the given endpoint.

        Each call to `write` with a non-empty message produces a single log event.
        """
        return self._wit_resource.write(msg)
