# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Cache Purging] API.

[Cache Purging]: https://www.fastly.com/documentation/guides/concepts/edge-state/cache/purging/
"""

from __future__ import annotations

from wit_world.imports import purge as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "PurgeOptions",
    "purge_surrogate_key",
    "purge_surrogate_key_verbose",
]


class PurgeOptions:
    """PurgeOptions."""

    def __init__(
        self,
        soft_purge: bool = False,
    ) -> None:
        self._wit = _wit.PurgeOptions(
            soft_purge=soft_purge,
            extra=None,
        )


class ExtraPurgeOptions(FastlyResource[_wit.ExtraPurgeOptions]):
    """Extensibility for `purge-options`"""


@remap_wit_errors(MAPPINGS)
def purge_surrogate_key(surrogate_keys: str, purge_options: PurgeOptions) -> None:
    """Purge a surrogate key for the current service.

    A surrogate key can be a max of 1024 characters.
    A surrogate key must contain only printable ASCII characters (those between `0x21` and `0x7E`,
    inclusive).

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.purge_surrogate_key(surrogate_keys, purge_options._wit)


@remap_wit_errors(MAPPINGS)
def purge_surrogate_key_verbose(
    surrogate_keys: str, purge_options: PurgeOptions, max_len: int
) -> str:
    """Purge a surrogate key for the current service, and return the purge id.

    This is similar to `purge_surrogate_key`, but on success, returns a
    [JSON purge response] containing an ASCII alphanumeric string identifying
    a purging.

    [JSON purge response]: https://developer.fastly.com/reference/api/purging/#purge-tag

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.purge_surrogate_key_verbose(surrogate_keys, purge_options._wit, max_len)
