# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Secret Store] API.

[Secret Store]: https://www.fastly.com/documentation/reference/api/services/resources/secret-store/
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import secret_store as _wit

from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "Secret",
    "Store",
]


class Secret(FastlyResource[_wit.Secret]):
    """An individual secret."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def from_bytes(cls, bytes: bytes) -> Self:
        """Creates a new “secret” from the given memory.

        This is *not* the suggested way to create `secret`s; instead, we suggest using `get`.
        This secret will *NOT* be shared with other sandboxes.

        This method can be used for data that should be secret, but is being obtained by
        some other means than the secret store. New “secrets” created this way use plaintext
        only, and live in the sandbox's memory unencrypted for much longer than secrets
        generated by `get`. They should thus only be used in situations in which an API requires
        a `secret`, but you cannot (for whatever reason) use a `store` to store them.

        As the early note says, this `secret` will be local to the current sandbox, and
        will not be shared with other instances of this service.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return cls(_wit.Secret.from_bytes(bytes))

    @remap_wit_errors(MAPPINGS)
    def plaintext(self, max_len: int) -> bytes:
        """Returns the plaintext value of this secret.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return self._wit_resource.plaintext(max_len)


class Store(FastlyResource[_wit.Store]):
    """A Secret Store."""

    @classmethod
    @remap_wit_errors(MAPPINGS)
    def open(cls, name: str) -> Self:
        """Opens the Secret Store with the given name.

        :raises ~fastly_compute.exceptions.types.open_error.OpenError:
        """
        return cls(_wit.Store.open(name))

    @remap_wit_errors(MAPPINGS)
    def get(self, key: str) -> Secret | None:
        """Tries to look up a Secret by name in this secret store.

        If successful, this method returns `s` containing the found secret `s` if the
        secret is found, or `None` if the secret was not found.

        :raises ~fastly_compute.exceptions.types.error.Error:
        """
        return Secret(self._wit_resource.get(key))
