# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Fastly Next-Gen WAF] API.

[Fastly Next-Gen WAF]: https://docs.fastly.com/en/ngwaf/
"""

from __future__ import annotations

from wit_world.imports import security as _wit
from wit_world.imports.types import IpAddress

from fastly_compute._bindings.async_io import Pollable
from fastly_compute._bindings.http_req import Request
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "InspectOptions",
    "IpAddress",
    "inspect",
]



class InspectOptions:
    """Configuration for inspecting a `request` using Security."""

    def __init__(
        self,
        corp: str | None = None,
        workspace: str | None = None,
        override_client_ip: IpAddress | None = None,
    ) -> None:
        self._wit = _wit.InspectOptions(
            corp=corp,
            workspace=workspace,
            override_client_ip=override_client_ip,
            extra=None,
        )


class ExtraInspectOptions(FastlyResource[_wit.ExtraInspectOptions]):
    """Extensibility for `inspect-options`"""


@remap_wit_errors(MAPPINGS)
def inspect(request: Request, body: Pollable, options: InspectOptions, max_len: int) -> str:
    """Inspects request HTTP traffic using the [NGWAF] lookaside service.

    Returns a JSON-encoded string.

    [NGWAF]: https://docs.fastly.com/en/ngwaf/

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.inspect(request._wit_resource, body._wit_resource, options._wit, max_len)

