# This file is automatically generated by scripts/generate_bindings.
# Do not edit directly.
"""[Shielding] API.

[Shielding]: https://www.fastly.com/documentation/guides/concepts/shielding/
"""

from __future__ import annotations

from typing import Self

from wit_world.imports import shielding as _wit

from fastly_compute._bindings.backend import Backend
from fastly_compute._error_mapping import MAPPINGS, remap_wit_errors
from fastly_compute._resource import FastlyResource

__all__ = [
    "ShieldBackendOptions",
    "backend_for_shield",
    "shield_info",
]




class ShieldBackendOptions(FastlyResource[_wit.ShieldBackendOptions]):
    """Options for `backend-for-shield`."""

    @classmethod
    def new(cls) -> Self:
        """Construct a new instance with default values."""
        return cls(_wit.ShieldBackendOptions())

    def set_cache_key(self, cache_key: str) -> None:
        """set_cache_key."""
        return self._wit_resource.set_cache_key(cache_key)

    def set_first_byte_timeout(self, timeout_ms: int) -> None:
        """set_first_byte_timeout."""
        return self._wit_resource.set_first_byte_timeout(timeout_ms)


@remap_wit_errors(MAPPINGS)
def shield_info(name: str, max_len: int) -> str:
    """shield_info.

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return _wit.shield_info(name, max_len)

@remap_wit_errors(MAPPINGS)
def backend_for_shield(name: str, options: ShieldBackendOptions | None) -> Backend:
    """backend_for_shield.

    :raises ~fastly_compute.exceptions.types.error.Error:
    """
    return Backend(_wit.backend_for_shield(name, options))

