# This file is automatically generated by scripts/generate_exceptions.
# It is not intended for manual editing.
"""Trailers aren't available until the body has been completely transmitted, so this error
type can either indicate that the errors aren't available yet, or that an error occurred.
"""

from fastly_compute.exceptions import FastlyError


class TrailerError(FastlyError):
    """Trailers aren't available until the body has been completely transmitted, so this error
    type can either indicate that the errors aren't available yet, or that an error occurred.
    """


class NotAvailableYet(TrailerError):
    """The trailers aren't available yet."""


class Error(TrailerError):
    """An error occurred."""
