"""A generator of Python code which improves upon the ergonomics and
idiomaticness of the WIT-derived code generated by componentize-py

This runs at SDK-build time; customers don't run it.

Generation is informed by the WIT. We considered informing it from
componentize-py's generated Python, but that turned out to be infeasibly lossy.
For example, for exception mapping, componentize-py's dataclasses and enum
members (which go into the .value properties of Err exceptions and correspond to
the more specific exceptions we'd like to raise) had nothing relating them to
methods except a brittle "Raises" docstring. And that docstring began to fail
with more complex error types, e.g. ones which are option<>s:
`wit_world.types.Err(wit_world.imports.Optional[Any])` is what comes out of
`result<_, option<trailer-error>>`.

On the surface, one downside of our chosen method is that we assume a stable
relationship of the WIT to componentize-py's generated stubs. But that must
remain stable, or callers would break. A true though slight downside is that
there are quite a few reimplemented bits of knowledge: WIT-interface-to-module
mappings, case conventions, and so on. Finally, there's the error-proneness of
JSON-struct-chasing and the need for wasm-tools. However, none of this is needed
beyond SDK build time, DRY code in the WIT processing should break spectacularly
if at all, and tests that touch any of the customer API should quickly reveal
such breakage.
"""
