"""Top level of the code-generation that makes exception-raising more idiomatic
in Fastly SDK routines

Handles high-level logic and writing to the filesystem.
"""

import json
from collections import defaultdict
from collections.abc import Iterable, Mapping
from pathlib import Path
from subprocess import check_output

from .wit import Function, NullType, Type, Wit

WIT_DIR = "wit"


def exception_code_tree(error_types: Iterable[Type]) -> Mapping[str, Mapping[str, str]]:
    """Generate Python exception classes we can map error types to.

    Inherit names and docstrings from the WIT. Create a common superclass for
    each type so you can catch the whole smear if you like.

    :arg error_types: An iterable of unique types used as error arms of
        ``result``s

    :return: A dict of package names pointing to module names pointing to
        contained code. For example, acl (from the interface name) -> acl_error.py
        (from the enum name) -> class AclError(FastlyError)...
    """
    # interface name -> module name -> code chunks:
    code = defaultdict(lambda: defaultdict(str))

    for error_type in error_types:
        package = error_type.py_package()
        module = error_type.py_module() + ".py"

        # Create package's empty __init__.py if not already there:
        code[package]["__init__.py"]

        if not code[package][module]:
            code[package][module] += (
                "from fastly_compute.exceptions import FastlyError\n\n\n"
            )

        # Common superclass for exceptions based on the enum or variant's
        # members. Or the raised exception itself for records.
        code[package][module] += (
            f"""class {error_type.py_exception_name()}(FastlyError):\n"""
            f'''    """{error_type.docstring_or_pass()}"""\n\n\n'''
        )
        # Insert enum or variant cases.
        for case in error_type.cases():
            code[package][module] += (
                f"""class {case.py_exception_name()}({error_type.py_exception_name()}):\n"""
                f'''    """{case.docstring_or_pass()}"""\n\n\n'''
            )
    return code


def mappings_code_tree(
    error_types: Iterable[Type], functions_to_patch: Iterable[Function]
) -> dict[str, dict[str, str]]:
    """Generate code which makes componentize-py-generated routines raise more
    specific, idiomatically shaped exceptions.

    Map componentize-py's Err values to specific exceptions. Generate
    monkeypatches that wrap componentize-py's generated Python routines to raise
    them.
    """
    code = (
        """# This file is automatically generated by generate_patches.py.\n"""
        """# It is not intended for manual editing.\n"""
        '''"""Monkeypatches which wrap the routines generated by componentize-py to make\n'''
        '''them raise more specific exceptions, not just Err."""\n\n'''
    )

    # Collect info:
    mappings = set()
    imports = set()
    for error_type in error_types:
        # Get where it is found in wit_world. Use shallow imports to avoid collisions.
        imports.add(error_type.wit_module_path())
        imports.add(error_type.py_module_path())
        if error_type.has_cases():
            # We need only add the cases; it doesn't make sense in WIT to return
            # the Enum or Variant itself in a result.
            for case in error_type.cases():
                mappings.add(
                    (
                        case.wit_path(),
                        error_type.py_module_path(),
                        case.py_exception_name(),
                    )
                )
        else:
            mappings.add(
                (
                    error_type.wit_path(),
                    error_type.py_module_path(),
                    error_type.py_exception_name(),
                )
            )

    # Collect import paths for the functions themselves:
    for func in functions_to_patch:
        imports.add(func.wit_module_path())

    # Do templating:
    code += "try:\n"
    code += (
        "    from .decorators import remap_wit_errors\n"
        "    import fastly_compute.exceptions\n"
    )
    for import_ in sorted(imports):
        code += f"    import {import_}\n"
    code += (
        "except ImportError:\n"
        "    # Tolerate that momentary import for the testrunner before Viceroy, and thus\n"
        "    # the wit_world, is around.\n"
        "    def patch():\n"
        '        print("Faking the run of exception-mapping monkeypatches for test runner.")\n'
        "else:\n"
        "    MAPPINGS = {\n"
    )
    for wit_path, py_module_path, py_exception_name in sorted(mappings):
        code += f"        {wit_path}: {py_module_path}.{py_exception_name},\n"
    code += (
        "        type(None): fastly_compute.exceptions.FastlyError,\n"  # Linter: don't wrap.
        "    }\n"
    )

    code += '''
    did_patch = False

    def patch():
        """Apply patches if they haven't already been applied."""

        global did_patch
        if did_patch:
            # This test shouldn't be needed, but it avoids double-wrapping the
            # routines if somehow patch() did get called twice.
            return
        did_patch = True\n\n'''

    for func in functions_to_patch:
        func_path = func.wit_path()
        code += f"        {func_path} = remap_wit_errors(MAPPINGS)({func_path})\n"

    # TODO: Make affordance for manually adding ergonomic getter properties,
    # __str__s, etc. to exception classes.

    # TODO: Maybe automatically improve the docstring of each method to list the
    # exceptions it raises.

    return {"wit_patching": {"patches.py": code}}


def write_files(tree: Mapping[str, Mapping[str, str]], base_folder: Path):
    """Create filesystem artifacts mirroring a nested dict representing folders,
    then files, then file contents.

    Overwrite files that are mentioned in ``tree``, but don't delete anything else.
    """
    for folder, files in tree.items():
        folder_path = base_folder / folder
        folder_path.mkdir(parents=True, exist_ok=True)
        for file, contents in files.items():
            file_path = folder_path / file
            file_path.write_text(contents)


def generate():
    """Generate idiomatic exceptions and monkeypatches to get WIT functions to
    raise them.

    Currently, this handles only ``result`` error types that are variants,
    enums, records, or the unit type. It doesn't handle options or primitives,
    but it would be straightfoward to expand as necessary. The only interesting
    decision to make when expanding is what kind of exception to raise: for
    enums, variants, and records, we generate an exception class corresponding
    to each case and raise that. But you can't raise a plain int. Maybe raise a
    generic FastlyError? We throw a NotImplementedError during generation if we
    do encounter something unsupported.
    """
    wit_text = check_output(["wasm-tools", "component", "wit", WIT_DIR, "--json"])
    wit_json = json.loads(wit_text)
    wit = Wit(wit_json)

    # A dict preserves order, for comprehensibility and determinism of generated code:
    exceptions_to_generate: dict[Type, bool] = {}
    functions_to_patch = []

    # Hunt through our whole fastly-compute package to find the result error
    # types we return. Each inspires the generation of one exception class (in
    # the case of records) or more (in the case of variants or enums).
    for interface in wit.fastly_compute_package().interfaces():
        for function in interface.functions():
            if error_type := function.error_type_of_returned_result():
                if not isinstance(error_type, NullType):
                    # Null errors (result<whatever, _>) are handled by a static
                    # entry mapping it to FastlyError.

                    # We don't need to go any deeper than the top-level type of
                    # the result's error. That represents the whole universe of
                    # Err values the componentize-py-generated bits may raise.
                    # Those values are what we will promote to exceptions.
                    exceptions_to_generate[error_type] = True
                    # Resource methods are shoved in here too but are
                    # identifiable:
                    functions_to_patch.append(function)

    fastly_compute = Path(__file__).parent.parent.parent / "fastly_compute"
    write_files(
        exception_code_tree(exceptions_to_generate.keys()),
        fastly_compute / "exceptions",
    )
    write_files(
        mappings_code_tree(exceptions_to_generate.keys(), functions_to_patch),
        fastly_compute,
    )
