name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: forge-amd64-medium
    steps:
    - uses: actions/checkout@v4
    - name: Set Up Rust Toolchain
    - name: Get wasiless submodule
      # Org-internal submodules are very tricky to check out.
      env:
        SSHK: ${{ secrets.WASILESS_REPO_READ_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$SSHK" > $HOME/.ssh/ssh.key
        chmod 600 $HOME/.ssh/ssh.key
        export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
        git submodule update --init --recursive
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: '1.86.0'
        target: wasm32-unknown-unknown
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv sync
    - name: Install wasm-tools and wac
      run: cargo install wasm-tools wac-cli
    - name: Install viceroy
      run: cargo install --git https://github.com/fastly/Viceroy.git --branch erik/python-sdk-2 viceroy
    - name: Install dependencies
      run: uv sync --extra dev --extra test
    - name: Check formatting
      run: make format-check
    - name: Run linting
      run: make lint
    - name: Run tests
      run: make test
